import {
	ArcHyperbolicSine,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const AHSin = ArcHyperbolicSine("Number")
const Arg = FromArgument("Integer")

// Generate an asinh operation object
const config = AHSin(Arg)

// Generate the composed asinh function
const calculate = composeOperators(config)

// Show the config object and the result
if (code) {
	code.innerHTML = `The configuration generated by ArcHyperbolicSine:

${JSON.stringify(config, null, 2)}

Get the asinh of 0:

calculate(0)

The return value: ${JSON.stringify(calculate(0), null, 2)}
`
}
