import { Tangent, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Tan = Tangent("Number")
const Arg = FromArgument("Number")

// Generate an tangent operation object
const config = Tan(Arg)

// Generate the composed tangent function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Tangent:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(0) ->", calculate(0))
