import { Round, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Round2 = Round("Number")(2)
const Arg = FromArgument("Number")

// Generate an round operation object
const config = Round2(Arg)

// Generate the composed round function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Round:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(11.223344) ->", calculate(11.223344))
// Five rounds up, four rounds down
console.log("calculate(-33.445566) ->", calculate(-33.445566))
