scrape_configs:
  # Docker container logs via docker_sd
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - target_label: 'env'
        replacement: 'dev'
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        replacement: '/var/lib/docker/containers/$1/$1-json.log'
    pipeline_stages:
      # Multiline for Java-style stack traces (Fuseki/others)
      - multiline:
          firstline: '^(?:\\d{4}-\\d{2}-\\d{2}|\\w{3} \\d{1,2}, \\d{4}|\\[[^\\]]+\\])'
      # Try JSON next; if parsing fails, keep raw
      - json:
          expressions:
            level: level
            msg: msg
            ts: time
        drop_malformed: false
      - labels:
          level:
          service:
          container:
      # Redact obvious secrets patterns (best-effort)
      - replace:
          expression: '(?i)(secret|password|token)[^\\n]*'
          replace: '$1=REDACTED'
      # Multiline for Java-style stack traces (Fuseki/others)
      - multiline:
          firstline: '^(?:\d{4}-\d{2}-\d{2}|\w{3} \d{1,2}, \d{4}|\[[^\]]+\])'
      # Redact obvious secrets patterns (best-effort)
      - replace:
          expression: '(?i)(secret|password|token)[^\n]*'
          replace: '$1=REDACTED'
