#!/usr/bin/env -S deno run --allow-read --allow-write

//++ Generates human-readable rules.md from rules.json

import { readFileSync, writeFileSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))

export default function generateRulesMarkdown(): void {
	// Read the rules.json file
	const rulesPath = join(__dirname, "..", "rules.json")
	const rulesContent = readFileSync(rulesPath, "utf-8")
	const rules = JSON.parse(rulesContent)
	
	// Build the markdown content
	const sections: Array<string> = []
	
	// Header
	sections.push(`# The @sitebender Rules

> **GENERATED FILE - DO NOT EDIT**
> 
> This file is automatically generated from \`rules.json\`.
> To make changes, edit \`rules.json\` and run \`deno task generate-rules\`.

**Version**: ${rules.version}  
**Last Updated**: ${rules.lastUpdated}  
**Author**: ${rules.author}

## Table of Contents

1. [The Prime Directive](#the-prime-directive)
2. [The Ten Commandments](#the-ten-commandments)
3. [Progressive Enhancement](#progressive-enhancement)
4. [Code Organization](#code-organization)
5. [Functional Programming](#functional-programming)
6. [Import Rules](#import-rules)
7. [Testing Requirements](#testing-requirements)
8. [The Seven Deadly Sins](#the-seven-deadly-sins)
9. [Error Handling](#error-handling)
10. [Data Privacy](#data-privacy)
11. [Git Workflow](#git-workflow)
12. [Code Style](#code-style)
13. [Envoy Comments](#envoy-comments)
14. [Cognitive Load](#cognitive-load)
15. [The Sacred Oath](#the-sacred-oath)
16. [Final Warnings](#final-warnings)`)
	
	// Prime Directive
	sections.push(`
## The Prime Directive

### ${rules.primeDirective.rule}

${rules.primeDirective.description}

${rules.primeDirective.rationale}

### The Cost of Your Assumptions

${rules.primeDirective.costs.map((cost: string) => `- **${cost}**`).join("\n")}

${rules.primeDirective.enforcement}`)
	
	// Ten Commandments
	sections.push(`
## The Ten Commandments

${rules.commandments.map((cmd: any) => `### ${cmd.id}. ${cmd.title}

${cmd.details.map((detail: string) => `- ${detail}`).join("\n")}`).join("\n\n")}`)
	
	// Progressive Enhancement
	sections.push(`
## Progressive Enhancement

### The Three Layers

${rules.progressiveEnhancement.layers.map((layer: any) => `#### Layer ${layer.level}: ${layer.name}
- **Description**: ${layer.description}
- **Requirement**: ${layer.requirement}`).join("\n\n")}

### Unbreakable Rules

${rules.progressiveEnhancement.unbreakableRules.map((rule: any) => `#### ${rule.rule}
${rule.details.map((detail: string) => `- ${detail}`).join("\n")}`).join("\n\n")}`)
	
	// Code Organization
	sections.push(`
## Code Organization

### The Immutable Laws

${rules.codeOrganization.laws.map((law: any) => `#### Law ${law.id}: ${law.name}

**Requirement**: ${law.requirement}

${law.example ? `**Example**:
- ✅ Correct: \`${law.example.correct}\`
- ❌ Incorrect: ${law.example.incorrect}` : ""}

${law.benefits ? `**Benefits**:
${law.benefits.map((benefit: string) => `- ${benefit}`).join("\n")}` : ""}

${law.exceptions ? `**Exceptions**:
${law.exceptions.map((exception: string) => `- ${exception}`).join("\n")}` : ""}

${law.rule || ""}`).join("\n\n")}

### Naming Conventions

- **Functions**: ${rules.codeOrganization.naming.functions}
- **Types**: ${rules.codeOrganization.naming.types}
- **Constants**: ${rules.codeOrganization.naming.constants}
- **Routes**: ${rules.codeOrganization.naming.routes}

**Forbidden**:
${rules.codeOrganization.naming.forbidden.map((item: string) => `- ${item}`).join("\n")}

### Barrel Files

**${rules.codeOrganization.barrelFiles}**`)
	
	// Functional Programming
	sections.push(`
## Functional Programming

### The Transition Prophecy

We're transitioning from **${rules.functionalProgramming.transitionProphecy.from}** to **${rules.functionalProgramming.transitionProphecy.to}**.

**Why?**
${rules.functionalProgramming.transitionProphecy.rationale.map((reason: string) => `- ${reason}`).join("\n")}

### Required Practices

${rules.functionalProgramming.required.map((req: string) => `- ${req}`).join("\n")}

### Forbidden Practices

${rules.functionalProgramming.forbidden.map((forbidden: string) => `- ${forbidden}`).join("\n")}`)
	
	// Import Rules
	sections.push(`
## Import Rules

### The Three Realms

#### Library Code
- **Internal imports**: ${rules.imports.realms.libraries.internal}
- **Other libraries**: ${rules.imports.realms.libraries.otherLibraries}
- **External deps**: ${rules.imports.realms.libraries.external}

#### Application Code
- **Internal imports**: ${rules.imports.realms.applications.internal}
- **Libraries**: ${rules.imports.realms.applications.libraries}
- **External deps**: ${rules.imports.realms.applications.external}

#### Test Code
- **Tested code**: ${rules.imports.realms.tests.testedCode}
- **Test deps**: ${rules.imports.realms.tests.testDeps}

### Import Commandments

${rules.imports.commandments.map((cmd: string) => `- ${cmd}`).join("\n")}`)
	
	// Testing
	sections.push(`
## Testing Requirements

### Coverage

**${rules.testing.coverage.requirement}**

${rules.testing.coverage.rationale}

Escape clause: ${rules.testing.coverage.escape}

### Testing Hierarchy

${rules.testing.hierarchy.map((level: string) => `1. **${level}**`).join("\n")}

### What to Test

${rules.testing.whatToTest.map((item: string) => `- ${item}`).join("\n")}

### What NOT to Test

${rules.testing.whatNotToTest.map((item: string) => `- ${item}`).join("\n")}

### Test Location

${rules.testing.location}`)
	
	// Seven Deadly Sins
	sections.push(`
## The Seven Deadly Sins

${rules.sevenDeadlySins.map((sin: any, index: number) => `### ${index + 1}. ${sin.sin}${sin.description ? ` - ${sin.description}` : ""}

**Examples of the sin**:
${sin.examples.map((ex: string) => `- ❌ ${ex}`).join("\n")}

**Solution**: ${sin.solution}`).join("\n\n")}`)
	
	// Error Handling
	sections.push(`
## Error Handling

### The Laws of Error Handling

${rules.errorHandling.laws.map((law: any) => `#### Law ${law.id}: ${law.law}

${law.details ? law.details.map((detail: string) => `- ${detail}`).join("\n") : ""}

${law.example ? `**Example**:
- ✅ Correct: \`${law.example.correct}\`
- ❌ Incorrect: \`${law.example.incorrect}\`` : ""}`).join("\n\n")}

### Recovery Strategies

${rules.errorHandling.recoveryStrategies.map((strategy: string) => `- ${strategy}`).join("\n")}`)
	
	// Data Privacy
	sections.push(`
## Data Privacy

### Local-First Principles

${rules.dataPrivacy.localFirst.map((principle: any) => `#### ${principle.principle}

${principle.details.map((detail: string) => `- ${detail}`).join("\n")}`).join("\n\n")}`)
	
	// Git Workflow
	sections.push(`
## Git Workflow

### Conventional Commits

**Required**: ${rules.git.conventionalCommits.required ? "Yes" : "No"}  
**Format**: \`${rules.git.conventionalCommits.format}\`  
**Types**: ${rules.git.conventionalCommits.types.join(", ")}

### Commit Rules

${rules.git.commitRules.map((rule: string) => `- ${rule}`).join("\n")}

### Pre-Commit Requirements

${rules.git.preCommitRequirements.map((req: string) => `- \`${req}\``).join("\n")}

**${rules.git.enforcement}**

### For AI Assistants

${rules.git.aiAssistants.note}

**Requirements**:
${rules.git.aiAssistants.requirements.map((req: string) => `- ${req}`).join("\n")}`)
	
	// Code Style
	sections.push(`
## Code Style

- **Indentation**: ${rules.codeStyle.indentation} (${rules.codeStyle.rationale.tabs})
- **Line limit**: ${rules.codeStyle.lineLimit} characters (${rules.codeStyle.rationale.lineLimit})
- **Semicolons**: ${rules.codeStyle.semicolons ? "Required" : "Forbidden"} (${rules.codeStyle.rationale.semicolons})
- **Array type**: ${rules.codeStyle.arrayType} (${rules.codeStyle.rationale.arrayType})
- **Variable declarations**: ${rules.codeStyle.constOnly ? "const only" : "let/const allowed"} (${rules.codeStyle.rationale.constOnly})`)
	
	// Envoy Comments
	sections.push(`
## Envoy Comments

| Syntax | Purpose |
|--------|---------|
${Object.entries(rules.envoyComments).map(([key, value]) => `| \`${key}\` | ${value} |`).join("\n")}`)
	
	// Cognitive Load
	sections.push(`
## Cognitive Load

### ${rules.cognitiveLoad.holyGrail}

### Why It Matters

${rules.cognitiveLoad.why.map((reason: string) => `- ${reason}`).join("\n")}

### How Every Rule Serves This Goal

${Object.entries(rules.cognitiveLoad.howRulesServe).map(([key, value]) => `- **${key.replace(/([A-Z])/g, " $1").trim()}**: ${value}`).join("\n")}

### The Test

${rules.cognitiveLoad.test}

### The Goal

**${rules.cognitiveLoad.goal}**`)
	
	// Sacred Oath
	sections.push(`
## The Sacred Oath

### ${rules.sacredOath.commitment}

${rules.sacredOath.oaths.map((oath: string) => `- ${oath}`).join("\n")}`)
	
	// Final Warnings
	sections.push(`
## Final Warnings

### Performance Constraints

${rules.finalWarnings.performanceConstraints}

### The Bottom Line

**${rules.finalWarnings.bottomLine}**

---

> _"${rules.finalWarnings.architectQuote}"_
> 
> — ${rules.author}`)
	
	// Write the file
	const outputPath = join(__dirname, "..", "rules.md")
	writeFileSync(outputPath, sections.join("\n"))
	
	console.log(`✅ Generated rules.md from rules.json`)
	console.log(`   Version: ${rules.version}`)
	console.log(`   Output: ${outputPath}`)
}

// Run if called directly
if (import.meta.main) {
	generateRulesMarkdown()
}