import {
	Exponent,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Exp = Exponent("Number")
const Arg = FromArgument("Number")

// Generate an exponent operation object
const config = Exp(Arg)

// Generate the composed exponent function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Exponent:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
// e^1 is 2.718281828459045...
console.log("calculate(1) ->", calculate(1))
