/*++
 + CSS styling generator
 + Generates CSS scaffolds for components following Sitebender patterns
 */

import type { CSSConfig, SubElement } from "./types.ts"
import { DEFAULT_CSS_CONFIG } from "./types.ts"

/*++
 + Convert PascalCase component name to kebab-case className
 + Example: "SubmitButton" => "submit-button"
 */
export function toKebabCase(componentName: string): string {
	return componentName
		.replace(/([A-Z])/g, "-$1")
		.toLowerCase()
		.replace(/^-/, "")
}

/*++
 + Generate header comment for CSS file
 */
function generateHeader(componentName: string): string {
	const lines = [
		"/*++",
		` + ${componentName} component styles`,
		" + Generated by css-styling generator",
		" */",
		"",
	]

	return lines.join("\n")
}

/*++
 + Generate Tier 3 property definitions in :root
 + Colors are specific, everything else uses shorthand
 + User can override these from their own :root block
 */
function generateTier3Properties(className: string) {
	return function generateTier3PropertiesWithClassName(includeAccessibility: boolean) {
		return function generateTier3PropertiesWithClassNameAndAccessibility(includePrint: boolean): string {
			const baseColorProps = [
				`\t--bend-${className}-background-color: var(--color-primary);`,
				`\t--bend-${className}-text-color: var(--color-text-inverse);`,
				`\t--bend-${className}-border-color: var(--color-primary-dark);`,
			]

			const baseShorthandProps = [
				`\t--bend-${className}-margin: 0;`,
				`\t--bend-${className}-padding: 1rem;`,
				`\t--bend-${className}-border: 0 solid var(--bend-${className}-border-color);`,
				`\t--bend-${className}-font: 600 1rem var(--font-body);`,
			]

			const accessibilityColorProps = includeAccessibility
				? [
					`\t--bend-${className}-focus-outline-color: var(--focus-color);`,
				]
				: []

			const accessibilityShorthandProps = includeAccessibility
				? [
					`\t--bend-${className}-focus-outline: 0.125rem solid var(--bend-${className}-focus-outline-color);`,
				]
				: []

			const printColorProps = includePrint
				? [
					`\t--bend-${className}-print-background-color: transparent;`,
					`\t--bend-${className}-print-text-color: #000;`,
					`\t--bend-${className}-print-border-color: #000;`,
				]
				: []

			const printShorthandProps = includePrint
				? [
					`\t--bend-${className}-print-border: 0.0625rem solid var(--bend-${className}-print-border-color);`,
				]
				: []

			const allProps = [
				...baseColorProps,
				...baseShorthandProps,
				...accessibilityColorProps,
				...accessibilityShorthandProps,
				...printColorProps,
				...printShorthandProps,
			]

			const lines = [
				"/*++ Tier 3 component properties - defined in :root for easy theming */",
				":root {",
				...allProps,
				"}",
				"",
			]

			return lines.join("\n")
		}
	}
}

/*++
 + Generate base component styles using Tier 3 properties
 + Properties are defined in :root, component just uses them
 */
function generateBaseStyles(className: string): string {
	const lines = [
		`/*++ Base component styles */`,
		`.bend-${className} {`,
		"\t/* IE11 fallback - great CSS with rem, NOT px */",
		"\tdisplay: block;",
		"\tmargin: 0;",
		"\tpadding: 1rem;",
		"\tbackground-color: #007bff;",
		"\tcolor: #fff;",
		"\tfont-size: 1rem;",
		"\tfont-weight: 600;",
		"\tborder: 0;",
		"",
		"\t/* Modern override - use Tier 3 properties */",
		`\tmargin: var(--bend-${className}-margin);`,
		`\tpadding: var(--bend-${className}-padding);`,
		`\tbackground-color: var(--bend-${className}-background-color);`,
		`\tcolor: var(--bend-${className}-text-color);`,
		`\tborder: var(--bend-${className}-border);`,
		`\tfont: var(--bend-${className}-font);`,
		"}",
		"",
	]

	return lines.join("\n")
}

/*++
 + Generate styles for a single sub-element
 */
function generateSubElementStyle(className: string): (subElement: SubElement) => string {
	return function generateStyleForSubElement(subElement: SubElement): string {
		const selector = subElement.selector
			? `${subElement.tagName}${subElement.selector}`
			: subElement.tagName

		const baseSelector = `.bend-${className} ${selector}`
		const lines = [`${baseSelector} {`, "\t/* Sub-element styles */", "}"]

		const stateLines = subElement.states
			? subElement.states.map(function mapState(state: string): string {
				return [`${baseSelector}:${state} {`, "\t/* State styles */", "}"].join("\n")
			})
			: []

		return [...lines, ...stateLines].join("\n")
	}
}

/*++
 + Generate sub-element styles section
 */
function generateSubElementStyles(className: string): (subElements: ReadonlyArray<SubElement>) => string {
	return function generateStylesForSubElements(subElements: ReadonlyArray<SubElement>): string {
		const header = "/*++ Sub-element styles */"

		const styles = subElements.map(generateSubElementStyle(className))

		const allLines = [header, ...styles, ""]

		return allLines.join("\n")
	}
}

/*++
 + Generate accessibility section
 + Uses Tier 3 properties defined in :root
 */
function generateAccessibilityStyles(className: string): string {
	const lines = [
		"/*++ Accessibility: Focus states */",
		`.bend-${className}:focus {`,
		"\t/* IE11 fallback */",
		"\toutline: 0.125rem solid #0056b3;",
		"",
		"\t/* Modern override - use Tier 3 property */",
		`\toutline: var(--bend-${className}-focus-outline);`,
		"}",
		"",
		"/*++ Accessibility: Touch targets (WCAG 2.5.5) */",
		`.bend-${className} {`,
		"\tmin-height: 3rem; /* 48px minimum */",
		"\tmin-width: 3rem;",
		"}",
		"",
		"/*++ Accessibility: Reduced motion (WCAG 2.3.3) */",
		"@media (prefers-reduced-motion: reduce) {",
		`\t.bend-${className} {`,
		"\t\tanimation: none;",
		"\t\ttransition: none;",
		"\t}",
		"}",
		"",
	]

	return lines.join("\n")
}

/*++
 + Generate print styles section
 + Uses Tier 3 properties defined in :root
 */
function generatePrintStyles(className: string): string {
	const lines = [
		"/*++ Print styles */",
		"@media print {",
		`\t.bend-${className} {`,
		"\t\t/* IE11 fallback */",
		"\t\tbackground-color: transparent;",
		"\t\tcolor: #000;",
		"\t\tborder: 0.0625rem solid #000;",
		"",
		"\t\t/* Modern override - use Tier 3 properties */",
		`\t\tbackground-color: var(--bend-${className}-print-background-color);`,
		`\t\tcolor: var(--bend-${className}-print-text-color);`,
		`\t\tborder: var(--bend-${className}-print-border);`,
		"\t}",
		"}",
		"",
	]

	return lines.join("\n")
}

/*++
 + Generate complete CSS for component
 + Takes CSSConfig and returns CSS string
 */
export function generateCSS(config: CSSConfig): string {
	const mergedConfig = {
		...DEFAULT_CSS_CONFIG,
		...config,
	}

	const className = mergedConfig.className || toKebabCase(mergedConfig.componentName)

	const sections = [
		generateHeader(mergedConfig.componentName),
		generateTier3Properties(className)(mergedConfig.includeAccessibility)(mergedConfig.includePrint),
		generateBaseStyles(className),
	]

	const subElementSection = mergedConfig.subElements && mergedConfig.subElements.length > 0
		? generateSubElementStyles(className)(mergedConfig.subElements)
		: ""

	const accessibilitySection = mergedConfig.includeAccessibility
		? generateAccessibilityStyles(className)
		: ""

	const printSection = mergedConfig.includePrint
		? generatePrintStyles(className)
		: ""

	const allSections = [
		...sections,
		subElementSection,
		accessibilitySection,
		printSection,
	].filter(function filterEmpty(section: string): boolean {
		return section.length > 0
	})

	return allSections.join("\n")
}
