/*++
 + CSS styling generator
 + Generates CSS scaffolds for components following Sitebender patterns
 */

import type { CSSConfig, SubElement } from "./types.ts"
import { DEFAULT_CSS_CONFIG } from "./types.ts"

/*++
 + Convert PascalCase component name to kebab-case className
 + Example: "SubmitButton" => "submit-button"
 */
export function toKebabCase(componentName: string): string {
	return componentName
		.replace(/([A-Z])/g, "-$1")
		.toLowerCase()
		.replace(/^-/, "")
}

/*++
 + Generate header comment for CSS file
 */
function generateHeader(componentName: string): string {
	const lines = [
		"/*++",
		` + ${componentName} component styles`,
		" + Generated by css-styling generator",
		" */",
		"",
	]

	return lines.join("\n")
}

/*++
 + Generate base component styles with Tier 3 properties IN the component class
 + Tier 3 references Tier 2 semantic tokens
 + Includes conditional properties for accessibility and print
 */
function generateBaseStyles(className: string, includeAccessibility: boolean, includePrint: boolean): string {
	const baseTier3Props = [
		`\t--bend-${className}-padding: var(--padding-default);`,
		`\t--bend-${className}-font-size: var(--font-size-body);`,
		`\t--bend-${className}-font-weight: var(--font-weight-semibold);`,
		`\t--bend-${className}-font-family: var(--font-body);`,
		`\t--bend-${className}-background-color: var(--color-primary);`,
		`\t--bend-${className}-color: var(--color-text-inverse);`,
	]

	const accessibilityTier3Props = includeAccessibility
		? [
			`\t--bend-${className}-focus-outline-color: var(--focus-color);`,
			`\t--bend-${className}-focus-outline-offset: var(--focus-offset);`,
		]
		: []

	const printTier3Props = includePrint
		? [
			`\t--bend-${className}-print-background-color: var(--print-background-color);`,
			`\t--bend-${className}-print-border-color: var(--print-border-color);`,
			`\t--bend-${className}-print-color: var(--print-text-color);`,
		]
		: []

	const allTier3Props = [
		...baseTier3Props,
		...accessibilityTier3Props,
		...printTier3Props,
	]

	const lines = [
		`/*++ Base component styles with Tier 3 component properties */`,
		`.bend-${className} {`,
		"\t/* Tier 3 - component properties reference Tier 2 semantic */",
		...allTier3Props,
		"",
		"\t/* IE11 fallback - great CSS with rem, NOT px */",
		"\tdisplay: block;",
		"\tpadding: 1rem;",
		"\tbackground-color: #007bff;",
		"\tcolor: #fff;",
		"\tfont-size: 1rem;",
		"\tfont-weight: 600;",
		"",
		"\t/* Modern override */",
		`\tpadding: var(--bend-${className}-padding);`,
		`\tfont-size: var(--bend-${className}-font-size);`,
		`\tfont-weight: var(--bend-${className}-font-weight);`,
		`\tfont-family: var(--bend-${className}-font-family);`,
		`\tbackground-color: var(--bend-${className}-background-color);`,
		`\tcolor: var(--bend-${className}-color);`,
		"}",
		"",
	]

	return lines.join("\n")
}

/*++
 + Generate styles for a single sub-element
 */
function generateSubElementStyle(className: string): (subElement: SubElement) => string {
	return function generateStyleForSubElement(subElement: SubElement): string {
		const selector = subElement.selector
			? `${subElement.tagName}${subElement.selector}`
			: subElement.tagName

		const baseSelector = `.bend-${className} ${selector}`
		const lines = [`${baseSelector} {`, "\t/* Sub-element styles */", "}"]

		const stateLines = subElement.states
			? subElement.states.map(function mapState(state: string): string {
				return [`${baseSelector}:${state} {`, "\t/* State styles */", "}"].join("\n")
			})
			: []

		return [...lines, ...stateLines].join("\n")
	}
}

/*++
 + Generate sub-element styles section
 */
function generateSubElementStyles(className: string): (subElements: ReadonlyArray<SubElement>) => string {
	return function generateStylesForSubElements(subElements: ReadonlyArray<SubElement>): string {
		const header = "/*++ Sub-element styles */"

		const styles = subElements.map(generateSubElementStyle(className))

		const allLines = [header, ...styles, ""]

		return allLines.join("\n")
	}
}

/*++
 + Generate accessibility section
 + Uses component-namespaced Tier 3 properties
 */
function generateAccessibilityStyles(className: string): string {
	const lines = [
		"/*++ Accessibility: Focus states */",
		`.bend-${className}:focus {`,
		"\t/* IE11 fallback */",
		"\toutline: 0.125rem solid #0056b3;",
		"\toutline-offset: 0.125rem;",
		"",
		"\t/* Modern override */",
		`\toutline: 0.125rem solid var(--bend-${className}-focus-outline-color);`,
		`\toutline-offset: var(--bend-${className}-focus-outline-offset);`,
		"}",
		"",
		"/*++ Accessibility: Touch targets */",
		`.bend-${className} {`,
		"\tmin-height: 3rem;",
		"\tmin-width: 3rem;",
		"}",
		"",
		"/*++ Accessibility: Reduced motion */",
		"@media (prefers-reduced-motion: reduce) {",
		`\t.bend-${className} {`,
		"\t\ttransition: none;",
		"\t}",
		"}",
		"",
	]

	return lines.join("\n")
}

/*++
 + Generate print styles section
 + Uses component-namespaced Tier 3 properties
 */
function generatePrintStyles(className: string): string {
	const lines = [
		"/*++ Print styles */",
		"@media print {",
		`\t.bend-${className} {`,
		"\t\t/* IE11 fallback */",
		"\t\tbackground-color: transparent;",
		"\t\tcolor: #000;",
		"\t\tborder: 0.0625rem solid #000;",
		"",
		"\t\t/* Modern override - use Tier 3 component print properties */",
		`\t\tbackground-color: var(--bend-${className}-print-background-color, transparent);`,
		`\t\tcolor: var(--bend-${className}-print-color, #000);`,
		`\t\tborder-color: var(--bend-${className}-print-border-color, #000);`,
		"\t}",
		"}",
		"",
	]

	return lines.join("\n")
}

/*++
 + Generate complete CSS for component
 + Takes CSSConfig and returns CSS string
 */
export function generateCSS(config: CSSConfig): string {
	const mergedConfig = {
		...DEFAULT_CSS_CONFIG,
		...config,
	}

	const className = mergedConfig.className || toKebabCase(mergedConfig.componentName)

	const sections = [
		generateHeader(mergedConfig.componentName),
		generateBaseStyles(className, mergedConfig.includeAccessibility, mergedConfig.includePrint),
	]

	const subElementSection = mergedConfig.subElements && mergedConfig.subElements.length > 0
		? generateSubElementStyles(className)(mergedConfig.subElements)
		: ""

	const accessibilitySection = mergedConfig.includeAccessibility
		? generateAccessibilityStyles(className)
		: ""

	const printSection = mergedConfig.includePrint
		? generatePrintStyles(className)
		: ""

	const allSections = [
		...sections,
		subElementSection,
		accessibilitySection,
		printSection,
	].filter(function filterEmpty(section: string): boolean {
		return section.length > 0
	})

	return allSections.join("\n")
}
