/*++
 + CSS styling generator
 + Generates CSS scaffolds for components following Sitebender patterns
 */

import type { CSSConfig, SubElement } from "./types.ts"
import { DEFAULT_CSS_CONFIG } from "./types.ts"

/*++
 + Convert PascalCase component name to kebab-case className
 + Example: "SubmitButton" => "submit-button"
 */
export function toKebabCase(componentName: string): string {
	return componentName
		.replace(/([A-Z])/g, "-$1")
		.toLowerCase()
		.replace(/^-/, "")
}

/*++
 + Generate header comment for CSS file
 */
function generateHeader(componentName: string): string {
	return function generateHeaderWithName(): string {
		const lines = [
			"/*++",
			` + ${componentName} component styles`,
			" + Generated by css-styling generator",
			" */",
			"",
		]

		return lines.join("\n")
	}()
}

/*++
 + Generate custom properties section
 + Tier 3 properties are STRUCTURAL ONLY - no colors
 */
function generateCustomProperties(className: string): string {
	return function generatePropertiesForClass(): string {
		const lines = [
			"/*++ Component custom properties (Tier 3 - structural only, NO colors) */",
			":root {",
			`\t--bend-${className}-padding: var(--bend-space-m);`,
			`\t--bend-${className}-font-size: 1rem;`,
			`\t--bend-${className}-font-weight: 600;`,
			"}",
			"",
		]

		return lines.join("\n")
	}()
}

/*++
 + Generate base component styles with IE11 fallback
 + Colors use Tier 2 semantic tokens directly - NOT component properties
 */
function generateBaseStyles(className: string): string {
	return function generateStylesForClass(): string {
		const lines = [
			"/*++ Component base styles */",
			`.bend-${className} {`,
			"\t/* IE11 fallback */",
			"\tdisplay: block;",
			"\tpadding: 1rem;",
			"\tbackground-color: #007bff;",
			"\tcolor: #fff;",
			"",
			"\t/* Modern override */",
			`\tpadding: var(--bend-${className}-padding);`,
			`\tfont-size: var(--bend-${className}-font-size);`,
			`\tfont-weight: var(--bend-${className}-font-weight);`,
			"\tbackground-color: var(--bend-color-primary);",
			"\tcolor: var(--bend-color-text-inverse);",
			"}",
			"",
		]

		return lines.join("\n")
	}()
}

/*++
 + Generate styles for a single sub-element
 */
function generateSubElementStyle(className: string): (subElement: SubElement) => string {
	return function generateStyleForSubElement(subElement: SubElement): string {
		const selector = subElement.selector
			? `${subElement.tagName}${subElement.selector}`
			: subElement.tagName

		const baseSelector = `.bend-${className} ${selector}`
		const lines = [`${baseSelector} {`, "\t/* Sub-element styles */", "}"]

		const stateLines = subElement.states
			? subElement.states.map(function mapState(state: string): string {
				return [`${baseSelector}:${state} {`, "\t/* State styles */", "}"].join("\n")
			})
			: []

		return [...lines, ...stateLines].join("\n")
	}
}

/*++
 + Generate sub-element styles section
 */
function generateSubElementStyles(className: string): (subElements: ReadonlyArray<SubElement>) => string {
	return function generateStylesForSubElements(subElements: ReadonlyArray<SubElement>): string {
		const header = "/*++ Sub-element styles */"

		const styles = subElements.map(generateSubElementStyle(className))

		const allLines = [header, ...styles, ""]

		return allLines.join("\n")
	}
}

/*++
 + Generate accessibility section
 */
function generateAccessibilityStyles(className: string): string {
	return function generateAccessibilityForClass(): string {
		const lines = [
			"/*++ Accessibility: Focus states */",
			`.bend-${className}:focus {`,
			"\toutline: 2px solid var(--bend-focus-color, #0056b3);",
			"\toutline-offset: 2px;",
			"}",
			"",
			"/*++ Accessibility: Touch targets */",
			`.bend-${className} {`,
			"\tmin-height: 48px;",
			"\tmin-width: 48px;",
			"}",
			"",
			"/*++ Accessibility: Reduced motion */",
			"@media (prefers-reduced-motion: reduce) {",
			`\t.bend-${className} {`,
			"\t\ttransition: none;",
			"\t}",
			"}",
			"",
		]

		return lines.join("\n")
	}()
}

/*++
 + Generate print styles section
 */
function generatePrintStyles(className: string): string {
	return function generatePrintForClass(): string {
		const lines = [
			"/*++ Print styles */",
			"@media print {",
			`\t.bend-${className} {`,
			"\t\t/* Print-optimized styles */",
			"\t\tbackground-color: transparent;",
			"\t\tcolor: var(--color-black);",
			"\t\tborder: 1px solid var(--color-black);",
			"\t}",
			"}",
			"",
		]

		return lines.join("\n")
	}()
}

/*++
 + Generate complete CSS for component
 + Takes CSSConfig and returns CSS string
 */
export function generateCSS(config: CSSConfig): string {
	const mergedConfig = {
		...DEFAULT_CSS_CONFIG,
		...config,
	}

	const className = mergedConfig.className || toKebabCase(mergedConfig.componentName)

	const sections = [
		generateHeader(mergedConfig.componentName),
		generateCustomProperties(className),
		generateBaseStyles(className),
	]

	const subElementSection = mergedConfig.subElements && mergedConfig.subElements.length > 0
		? generateSubElementStyles(className)(mergedConfig.subElements)
		: ""

	const accessibilitySection = mergedConfig.includeAccessibility
		? generateAccessibilityStyles(className)
		: ""

	const printSection = mergedConfig.includePrint
		? generatePrintStyles(className)
		: ""

	const allSections = [
		...sections,
		subElementSection,
		accessibilitySection,
		printSection,
	].filter(function filterEmpty(section: string): boolean {
		return section.length > 0
	})

	return allSections.join("\n")
}
