type: S3
config:
  bucket: "thanos" # The bucket name we created (or will be created automatically)
  endpoint: "minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  insecure: true # Uses HTTP instead of HTTPS, which is fine for local development
  signature_version2: false