auth_enabled: false
server:
    http_listen_port: 3100
    log_level: info
common:
    path_prefix: /loki
    storage:
        filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
    replication_factor: 1
    ring:
        instance_addr: 127.0.0.1
        kvstore:
            store: inmemory
schema_config:
    configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
              prefix: index_
              period: 24h
ruler:
    alertmanager_url: http://prometheus:9093 # not used; placeholder
limits_config:
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 16
    max_global_streams_per_user: 0
    max_label_names_per_series: 30
    reject_old_samples: true
    reject_old_samples_max_age: 168h
chunk_store_config:
    max_look_back_period: 720h
compactor:
    working_directory: /loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
table_manager:
    retention_deletes_enabled: true
    retention_period: 336h # 14d dev default
