import { Floor, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Floor2 = Floor("Number")(2)
const Arg = FromArgument("Number")

// Generate an floor operation object
const config = Floor2(Arg)

// Generate the composed floor function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Floor:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log(
	"floor(33.445566) ===",
	JSON.stringify(calculate(33.445566), null, 2),
)
// Floor is toward -Infinity (compare with Truncate)
console.log(
	"Toward -Infinity:\n",
	"floor(-33.445566) ===",
	JSON.stringify(calculate(-33.445566), null, 2),
)
