import {
	ArcHyperbolicCosine,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const AHCos = ArcHyperbolicCosine("Number")
const Arg = FromArgument("Number")

// Generate an acosh operation object
const config = AHCos(Arg)

// Generate the composed acosh function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by ArcHyperbolicCosine:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(1) ->", calculate(1))
