import {
	ArcHyperbolicCosine,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const AHCos = ArcHyperbolicCosine("Number")
const Arg = FromArgument("Integer")

// Generate an acosh operation object
const config = AHCos(Arg)

// Generate the composed acosh function
const calculate = composeOperators(config)

// Show the config object and the result
if (code) {
	code.innerHTML = `The configuration generated by ArcHyperbolicCosine:

${JSON.stringify(config, null, 2)}

Get the acosh of 1:

calculate(1)

The return value: ${JSON.stringify(calculate(1), null, 2)}
`
}
