import type {
	BaseComponentProps,
	ExtractLevelProps,
} from "../../../types/index.ts"
import type ThingProps from "../../../types/Thing/index.ts"
import type OrganizationProps from "../../../types/Thing/Organization/index.ts"

import Base from "../../Base/index.tsx"
import Thing from "../index.tsx"

export type Props = BaseComponentProps<
	OrganizationProps,
	"Organization",
	ExtractLevelProps<OrganizationProps, ThingProps>
>

export default function Organization(props: Props) {
	const {
		actionableFeedbackPolicy,
		address,
		agentInteractionStatistic,
		aggregateRating,
		alumni,
		areaServed,
		award,
		awards,
		brand,
		contactPoint,
		contactPoints,
		correctionsPolicy,
		department,
		dissolutionDate,
		diversityPolicy,
		diversityStaffingReport,
		duns,
		email,
		employee,
		employees,
		ethicsPolicy,
		event,
		events,
		faxNumber,
		founder,
		founders,
		founding,
		foundingDate,
		foundingLocation,
		funder,
		funding,
		globalLocationNumber,
		hasCertification,
		hasCredential,
		hasMerchantReturnPolicy,
		hasOfferCatalog,
		hasPOS,
		interactionStatistic,
		isicV4,
		iso6523Code,
		keywords,
		knowsAbout,
		knowsLanguage,
		legalName,
		leiCode,
		location,
		logo,
		makesOffer,
		member,
		memberOf,
		members,
		naics,
		nonprofitStatus,
		numberOfEmployees,
		ownershipFundingInfo,
		owns,
		parentOrganization,
		publishingPrinciples,
		review,
		reviews,
		seeks,
		serviceArea,
		slogan,
		sponsor,
		subOrganization,
		taxID,
		telephone,
		unnamedSourcesPolicy,
		vatID,
		format,
		...restProps
	} = props

	const thingData = Thing(restProps)

	return (
		<Base
			element="span"
			format={format || "{{name}}"}
			props={{
				...thingData.props,
				actionableFeedbackPolicy,
				address,
				agentInteractionStatistic,
				aggregateRating,
				alumni,
				areaServed,
				award,
				awards,
				brand,
				contactPoint,
				contactPoints,
				correctionsPolicy,
				department,
				dissolutionDate,
				diversityPolicy,
				diversityStaffingReport,
				duns,
				email,
				employee,
				employees,
				ethicsPolicy,
				event,
				events,
				faxNumber,
				founder,
				founders,
				founding,
				foundingDate,
				foundingLocation,
				funder,
				funding,
				globalLocationNumber,
				hasCertification,
				hasCredential,
				hasMerchantReturnPolicy,
				hasOfferCatalog,
				hasPOS,
				interactionStatistic,
				isicV4,
				iso6523Code,
				keywords,
				knowsAbout,
				knowsLanguage,
				legalName,
				leiCode,
				location,
				logo,
				makesOffer,
				member,
				memberOf,
				members,
				naics,
				nonprofitStatus,
				numberOfEmployees,
				ownershipFundingInfo,
				owns,
				parentOrganization,
				publishingPrinciples,
				review,
				reviews,
				seeks,
				serviceArea,
				slogan,
				sponsor,
				subOrganization,
				taxID,
				telephone,
				unnamedSourcesPolicy,
				vatID,
			}}
		/>
	)
}
