import {
	composeOperators,
	Constant,
	Power,
	FromArgument,
	Multiply,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Product = Multiply("Integer")
const Pow = Power("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate a power operation with nested multiplication
// from constants and the passed argument
const config = Pow(Product([Int(2), Int(3)]))(Arg)

// Generate the calculate function by passing
// the operation object to composeOperators
const calculate = composeOperators(config)

// Show the config object and the product
const out =
	"The configuration generated by Power:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log(JSON.stringify(calculate(2), null, 2))
