import {
	AbsoluteValue,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Abs = AbsoluteValue("Number")
const Arg = FromArgument("Integer")

// Generate an absolute value operation object
const config = Abs(Arg)

// Generate the composed absolute value function
const calculate = composeOperators(config)

// Show the config object and the sum
if (code) {
	code.innerHTML = `The configuration generated by AbsoluteValue:

${JSON.stringify(config, null, 2)}

Get the absolute value of -1:

calculate(-1)

The return value: ${JSON.stringify(calculate(-1), null, 2)}
`
}
