import {
	AbsoluteValue,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Abs = AbsoluteValue("Number")
const Arg = FromArgument("Number")

// Generate an absolute value operation object
const config = Abs(Arg)

// Generate the composed absolute value function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by AbsoluteValue:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("absoluteValue(1) ===", JSON.stringify(calculate(1), null, 2))
console.log("absoluteValue(-1) ===", JSON.stringify(calculate(-1), null, 2))
