import {
	Truncate,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Trunc2 = Truncate("Number")(2)
const Arg = FromArgument("Number")

// Generate an truncate operation object
const config = Trunc2(Arg)

// Generate the composed truncate function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Truncate:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(33.445566) ->", calculate(33.445566))
// Truncate is toward zero (compare with Floor)
console.log("calculate(-33.445566) ->", calculate(-33.445566))
