//++ ISO 3166 country codes with international dialing prefixes
export const COUNTRY_AND_DIALING_CODES = [
	{
		name: "Afghanistan",
		alpha2: "AF",
		alpha3: "AFG",
		numeric: "004",
		dialingCode: "+93",
	},
	{
		name: "Albania",
		alpha2: "AL",
		alpha3: "ALB",
		numeric: "008",
		dialingCode: "+355",
	},
	{
		name: "Algeria",
		alpha2: "DZ",
		alpha3: "DZA",
		numeric: "012",
		dialingCode: "+213",
	},
	{
		name: "American Samoa",
		alpha2: "AS",
		alpha3: "ASM",
		numeric: "016",
		dialingCode: "+1 684",
	},
	{
		name: "Andorra",
		alpha2: "AD",
		alpha3: "AND",
		numeric: "020",
		dialingCode: "+376",
	},
	{
		name: "Angola",
		alpha2: "AO",
		alpha3: "AGO",
		numeric: "024",
		dialingCode: "+244",
	},
	{
		name: "Anguilla",
		alpha2: "AI",
		alpha3: "AIA",
		numeric: "660",
		dialingCode: "+1 264",
	},
	{
		name: "Antarctica",
		alpha2: "AQ",
		alpha3: "ATA",
		numeric: "010",
		dialingCode: "+672",
	},
	{
		name: "Antigua and Barbuda",
		alpha2: "AG",
		alpha3: "ATG",
		numeric: "028",
		dialingCode: "+1 268",
	},
	{
		name: "Argentina",
		alpha2: "AR",
		alpha3: "ARG",
		numeric: "032",
		dialingCode: "+54",
	},
	{
		name: "Armenia",
		alpha2: "AM",
		alpha3: "ARM",
		numeric: "051",
		dialingCode: "+374",
	},
	{
		name: "Aruba",
		alpha2: "AW",
		alpha3: "ABW",
		numeric: "533",
		dialingCode: "+297",
	},
	{
		name: "Australia",
		alpha2: "AU",
		alpha3: "AUS",
		numeric: "036",
		dialingCode: "+61",
	},
	{
		name: "Austria",
		alpha2: "AT",
		alpha3: "AUT",
		numeric: "040",
		dialingCode: "+43",
	},
	{
		name: "Azerbaijan",
		alpha2: "AZ",
		alpha3: "AZE",
		numeric: "031",
		dialingCode: "+994",
	},
	{
		name: "Bahamas",
		alpha2: "BS",
		alpha3: "BHS",
		numeric: "044",
		dialingCode: "+1 242",
	},
	{
		name: "Bahrain",
		alpha2: "BH",
		alpha3: "BHR",
		numeric: "048",
		dialingCode: "+973",
	},
	{
		name: "Bangladesh",
		alpha2: "BD",
		alpha3: "BGD",
		numeric: "050",
		dialingCode: "+880",
	},
	{
		name: "Barbados",
		alpha2: "BB",
		alpha3: "BRB",
		numeric: "052",
		dialingCode: "+1 246",
	},
	{
		name: "Belarus",
		alpha2: "BY",
		alpha3: "BLR",
		numeric: "112",
		dialingCode: "+375",
	},
	{
		name: "Belgium",
		alpha2: "BE",
		alpha3: "BEL",
		numeric: "056",
		dialingCode: "+32",
	},
	{
		name: "Belize",
		alpha2: "BZ",
		alpha3: "BLZ",
		numeric: "084",
		dialingCode: "+501",
	},
	{
		name: "Benin",
		alpha2: "BJ",
		alpha3: "BEN",
		numeric: "204",
		dialingCode: "+229",
	},
	{
		name: "Bermuda",
		alpha2: "BM",
		alpha3: "BMU",
		numeric: "060",
		dialingCode: "+1 441",
	},
	{
		name: "Bhutan",
		alpha2: "BT",
		alpha3: "BTN",
		numeric: "064",
		dialingCode: "+975",
	},
	{
		name: "Bolivia",
		alpha2: "BO",
		alpha3: "BOL",
		numeric: "068",
		dialingCode: "+591",
	},
	{
		name: "Bosnia and Herzegovina",
		alpha2: "BA",
		alpha3: "BIH",
		numeric: "070",
		dialingCode: "+387",
	},
	{
		name: "Botswana",
		alpha2: "BW",
		alpha3: "BWA",
		numeric: "072",
		dialingCode: "+267",
	},
	{
		name: "Brazil",
		alpha2: "BR",
		alpha3: "BRA",
		numeric: "076",
		dialingCode: "+55",
	},
	{
		name: "British Indian Ocean Territory",
		alpha2: "IO",
		alpha3: "IOT",
		numeric: "086",
		dialingCode: "+246",
	},
	{
		name: "Brunei Darussalam",
		alpha2: "BN",
		alpha3: "BRN",
		numeric: "096",
		dialingCode: "+673",
	},
	{
		name: "Bulgaria",
		alpha2: "BG",
		alpha3: "BGR",
		numeric: "100",
		dialingCode: "+359",
	},
	{
		name: "Burkina Faso",
		alpha2: "BF",
		alpha3: "BFA",
		numeric: "854",
		dialingCode: "+226",
	},
	{
		name: "Burundi",
		alpha2: "BI",
		alpha3: "BDI",
		numeric: "108",
		dialingCode: "+257",
	},
	{
		name: "Cabo Verde",
		alpha2: "CV",
		alpha3: "CPV",
		numeric: "132",
		dialingCode: "+238",
	},
	{
		name: "Cambodia",
		alpha2: "KH",
		alpha3: "KHM",
		numeric: "116",
		dialingCode: "+855",
	},
	{
		name: "Cameroon",
		alpha2: "CM",
		alpha3: "CMR",
		numeric: "120",
		dialingCode: "+237",
	},
	{
		name: "Canada",
		alpha2: "CA",
		alpha3: "CAN",
		numeric: "124",
		dialingCode: "+1",
	},
	{
		name: "Cayman Islands",
		alpha2: "KY",
		alpha3: "CYM",
		numeric: "136",
		dialingCode: "+1 345",
	},
	{
		name: "Central African Republic",
		alpha2: "CF",
		alpha3: "CAF",
		numeric: "140",
		dialingCode: "+236",
	},
	{
		name: "Chad",
		alpha2: "TD",
		alpha3: "TCD",
		numeric: "148",
		dialingCode: "+235",
	},
	{
		name: "Chile",
		alpha2: "CL",
		alpha3: "CHL",
		numeric: "152",
		dialingCode: "+56",
	},
	{
		name: "China",
		alpha2: "CN",
		alpha3: "CHN",
		numeric: "156",
		dialingCode: "+86",
	},
	{
		name: "Christmas Island",
		alpha2: "CX",
		alpha3: "CXR",
		numeric: "162",
		dialingCode: "+61",
	},
	{
		name: "Cocos (Keeling) Islands",
		alpha2: "CC",
		alpha3: "CCK",
		numeric: "166",
		dialingCode: "+61",
	},
	{
		name: "Colombia",
		alpha2: "CO",
		alpha3: "COL",
		numeric: "170",
		dialingCode: "+57",
	},
	{
		name: "Comoros",
		alpha2: "KM",
		alpha3: "COM",
		numeric: "174",
		dialingCode: "+269",
	},
	{
		name: "Congo",
		alpha2: "CG",
		alpha3: "COG",
		numeric: "178",
		dialingCode: "+242",
	},
	{
		name: "Congo (Democratic Republic of the)",
		alpha2: "CD",
		alpha3: "COD",
		numeric: "180",
		dialingCode: "+243",
	},
	{
		name: "Cook Islands",
		alpha2: "CK",
		alpha3: "COK",
		numeric: "184",
		dialingCode: "+682",
	},
	{
		name: "Costa Rica",
		alpha2: "CR",
		alpha3: "CRI",
		numeric: "188",
		dialingCode: "+506",
	},
	{
		name: "Croatia",
		alpha2: "HR",
		alpha3: "HRV",
		numeric: "191",
		dialingCode: "+385",
	},
	{
		name: "Cuba",
		alpha2: "CU",
		alpha3: "CUB",
		numeric: "192",
		dialingCode: "+53",
	},
	{
		name: "Curaçao",
		alpha2: "CW",
		alpha3: "CUW",
		numeric: "531",
		dialingCode: "+599",
	},
	{
		name: "Cyprus",
		alpha2: "CY",
		alpha3: "CYP",
		numeric: "196",
		dialingCode: "+357",
	},
	{
		name: "Czech Republic",
		alpha2: "CZ",
		alpha3: "CZE",
		numeric: "203",
		dialingCode: "+420",
	},
	{
		name: "Denmark",
		alpha2: "DK",
		alpha3: "DNK",
		numeric: "208",
		dialingCode: "+45",
	},
	{
		name: "Djibouti",
		alpha2: "DJ",
		alpha3: "DJI",
		numeric: "262",
		dialingCode: "+253",
	},
	{
		name: "Dominica",
		alpha2: "DM",
		alpha3: "DMA",
		numeric: "212",
		dialingCode: "+1 767",
	},
	{
		name: "Dominican Republic",
		alpha2: "DO",
		alpha3: "DOM",
		numeric: "214",
		dialingCode: "+1 809",
	},
	{
		name: "Dominican Republic",
		alpha2: "DO",
		alpha3: "DOM",
		numeric: "214",
		dialingCode: "+1 829",
	},
	{
		name: "Dominican Republic",
		alpha2: "DO",
		alpha3: "DOM",
		numeric: "214",
		dialingCode: "+1 849",
	},
	{
		name: "Ecuador",
		alpha2: "EC",
		alpha3: "ECU",
		numeric: "218",
		dialingCode: "+593",
	},
	{
		name: "Egypt",
		alpha2: "EG",
		alpha3: "EGY",
		numeric: "818",
		dialingCode: "+20",
	},
	{
		name: "El Salvador",
		alpha2: "SV",
		alpha3: "SLV",
		numeric: "222",
		dialingCode: "+503",
	},
	{
		name: "Equatorial Guinea",
		alpha2: "GQ",
		alpha3: "GNQ",
		numeric: "226",
		dialingCode: "+240",
	},
	{
		name: "Eritrea",
		alpha2: "ER",
		alpha3: "ERI",
		numeric: "232",
		dialingCode: "+291",
	},
	{
		name: "Estonia",
		alpha2: "EE",
		alpha3: "EST",
		numeric: "233",
		dialingCode: "+372",
	},
	{
		name: "Eswatini",
		alpha2: "SZ",
		alpha3: "SWZ",
		numeric: "748",
		dialingCode: "+268",
	},
	{
		name: "Ethiopia",
		alpha2: "ET",
		alpha3: "ETH",
		numeric: "231",
		dialingCode: "+251",
	},
	{
		name: "Falkland Islands (Malvinas)",
		alpha2: "FK",
		alpha3: "FLK",
		numeric: "238",
		dialingCode: "+500",
	},
	{
		name: "Faroe Islands",
		alpha2: "FO",
		alpha3: "FRO",
		numeric: "234",
		dialingCode: "+298",
	},
	{
		name: "Fiji",
		alpha2: "FJ",
		alpha3: "FJI",
		numeric: "242",
		dialingCode: "+679",
	},
	{
		name: "Finland",
		alpha2: "FI",
		alpha3: "FIN",
		numeric: "246",
		dialingCode: "+358",
	},
	{
		name: "France",
		alpha2: "FR",
		alpha3: "FRA",
		numeric: "250",
		dialingCode: "+33",
	},
	{
		name: "French Guiana",
		alpha2: "GF",
		alpha3: "GUF",
		numeric: "254",
		dialingCode: "+594",
	},
	{
		name: "French Polynesia",
		alpha2: "PF",
		alpha3: "PYF",
		numeric: "258",
		dialingCode: "+689",
	},
	{
		name: "French Southern Territories",
		alpha2: "TF",
		alpha3: "ATF",
		numeric: "260",
		dialingCode: "+262",
	},
	{
		name: "Gabon",
		alpha2: "GA",
		alpha3: "GAB",
		numeric: "266",
		dialingCode: "+241",
	},
	{
		name: "Gambia",
		alpha2: "GM",
		alpha3: "GMB",
		numeric: "270",
		dialingCode: "+220",
	},
	{
		name: "Georgia",
		alpha2: "GE",
		alpha3: "GEO",
		numeric: "268",
		dialingCode: "+995",
	},
	{
		name: "Germany",
		alpha2: "DE",
		alpha3: "DEU",
		numeric: "276",
		dialingCode: "+49",
	},
	{
		name: "Ghana",
		alpha2: "GH",
		alpha3: "GHA",
		numeric: "288",
		dialingCode: "+233",
	},
	{
		name: "Gibraltar",
		alpha2: "GI",
		alpha3: "GIB",
		numeric: "292",
		dialingCode: "+350",
	},
	{
		name: "Greece",
		alpha2: "GR",
		alpha3: "GRC",
		numeric: "300",
		dialingCode: "+30",
	},
	{
		name: "Greenland",
		alpha2: "GL",
		alpha3: "GRL",
		numeric: "304",
		dialingCode: "+299",
	},
	{
		name: "Grenada",
		alpha2: "GD",
		alpha3: "GRD",
		numeric: "308",
		dialingCode: "+1 473",
	},
	{
		name: "Guadeloupe",
		alpha2: "GP",
		alpha3: "GLP",
		numeric: "312",
		dialingCode: "+590",
	},
	{
		name: "Guam",
		alpha2: "GU",
		alpha3: "GUM",
		numeric: "316",
		dialingCode: "+1 671",
	},
	{
		name: "Guatemala",
		alpha2: "GT",
		alpha3: "GTM",
		numeric: "320",
		dialingCode: "+502",
	},
	{
		name: "Guernsey",
		alpha2: "GG",
		alpha3: "GGY",
		numeric: "831",
		dialingCode: "+44",
	},
	{
		name: "Guinea",
		alpha2: "GN",
		alpha3: "GIN",
		numeric: "324",
		dialingCode: "+224",
	},
	{
		name: "Guinea-Bissau",
		alpha2: "GW",
		alpha3: "GNB",
		numeric: "624",
		dialingCode: "+245",
	},
	{
		name: "Guyana",
		alpha2: "GY",
		alpha3: "GUY",
		numeric: "328",
		dialingCode: "+592",
	},
	{
		name: "Haiti",
		alpha2: "HT",
		alpha3: "HTI",
		numeric: "332",
		dialingCode: "+509",
	},
	{
		name: "Heard Island and McDonald Islands",
		alpha2: "HM",
		alpha3: "HMD",
		numeric: "334",
		dialingCode: "+672",
	},
	{
		name: "Holy See",
		alpha2: "VA",
		alpha3: "VAT",
		numeric: "336",
		dialingCode: "+379",
	},
	{
		name: "Honduras",
		alpha2: "HN",
		alpha3: "HND",
		numeric: "340",
		dialingCode: "+504",
	},
	{
		name: "Hong Kong",
		alpha2: "HK",
		alpha3: "HKG",
		numeric: "344",
		dialingCode: "+852",
	},
	{
		name: "Hungary",
		alpha2: "HU",
		alpha3: "HUN",
		numeric: "348",
		dialingCode: "+36",
	},
	{
		name: "Iceland",
		alpha2: "IS",
		alpha3: "ISL",
		numeric: "352",
		dialingCode: "+354",
	},
	{
		name: "India",
		alpha2: "IN",
		alpha3: "IND",
		numeric: "356",
		dialingCode: "+91",
	},
	{
		name: "Indonesia",
		alpha2: "ID",
		alpha3: "IDN",
		numeric: "360",
		dialingCode: "+62",
	},
	{
		name: "Iran (Islamic Republic of)",
		alpha2: "IR",
		alpha3: "IRN",
		numeric: "364",
		dialingCode: "+98",
	},
	{
		name: "Iraq",
		alpha2: "IQ",
		alpha3: "IRQ",
		numeric: "368",
		dialingCode: "+964",
	},
	{
		name: "Ireland",
		alpha2: "IE",
		alpha3: "IRL",
		numeric: "372",
		dialingCode: "+353",
	},
	{
		name: "Isle of Man",
		alpha2: "IM",
		alpha3: "IMN",
		numeric: "833",
		dialingCode: "+44",
	},
	{
		name: "Israel",
		alpha2: "IL",
		alpha3: "ISR",
		numeric: "376",
		dialingCode: "+972",
	},
	{
		name: "Italy",
		alpha2: "IT",
		alpha3: "ITA",
		numeric: "380",
		dialingCode: "+39",
	},
	{
		name: "Jamaica",
		alpha2: "JM",
		alpha3: "JAM",
		numeric: "388",
		dialingCode: "+1 876",
	},
	{
		name: "Japan",
		alpha2: "JP",
		alpha3: "JPN",
		numeric: "392",
		dialingCode: "+81",
	},
	{
		name: "Jersey",
		alpha2: "JE",
		alpha3: "JEY",
		numeric: "832",
		dialingCode: "+44",
	},
	{
		name: "Jordan",
		alpha2: "JO",
		alpha3: "JOR",
		numeric: "400",
		dialingCode: "+962",
	},
	{
		name: "Kazakhstan",
		alpha2: "KZ",
		alpha3: "KAZ",
		numeric: "398",
		dialingCode: "+7",
	},
	{
		name: "Kenya",
		alpha2: "KE",
		alpha3: "KEN",
		numeric: "404",
		dialingCode: "+254",
	},
	{
		name: "Kiribati",
		alpha2: "KI",
		alpha3: "KIR",
		numeric: "296",
		dialingCode: "+686",
	},
	{
		name: "Korea (Democratic People's Republic of)",
		alpha2: "KP",
		alpha3: "PRK",
		numeric: "408",
		dialingCode: "+850",
	},
	{
		name: "Korea (Republic of)",
		alpha2: "KR",
		alpha3: "KOR",
		numeric: "410",
		dialingCode: "+82",
	},
	{
		name: "Kuwait",
		alpha2: "KW",
		alpha3: "KWT",
		numeric: "414",
		dialingCode: "+965",
	},
	{
		name: "Kyrgyzstan",
		alpha2: "KG",
		alpha3: "KGZ",
		numeric: "417",
		dialingCode: "+996",
	},
	{
		name: "Lao People's Democratic Republic",
		alpha2: "LA",
		alpha3: "LAO",
		numeric: "418",
		dialingCode: "+856",
	},
	{
		name: "Latvia",
		alpha2: "LV",
		alpha3: "LVA",
		numeric: "428",
		dialingCode: "+371",
	},
	{
		name: "Lebanon",
		alpha2: "LB",
		alpha3: "LBN",
		numeric: "422",
		dialingCode: "+961",
	},
	{
		name: "Lesotho",
		alpha2: "LS",
		alpha3: "LSO",
		numeric: "426",
		dialingCode: "+266",
	},
	{
		name: "Liberia",
		alpha2: "LR",
		alpha3: "LBR",
		numeric: "430",
		dialingCode: "+231",
	},
	{
		name: "Libya",
		alpha2: "LY",
		alpha3: "LBY",
		numeric: "434",
		dialingCode: "+218",
	},
	{
		name: "Liechtenstein",
		alpha2: "LI",
		alpha3: "LIE",
		numeric: "438",
		dialingCode: "+423",
	},
	{
		name: "Lithuania",
		alpha2: "LT",
		alpha3: "LTU",
		numeric: "440",
		dialingCode: "+370",
	},
	{
		name: "Luxembourg",
		alpha2: "LU",
		alpha3: "LUX",
		numeric: "442",
		dialingCode: "+352",
	},
	{
		name: "Macao",
		alpha2: "MO",
		alpha3: "MAC",
		numeric: "446",
		dialingCode: "+853",
	},
	{
		name: "Madagascar",
		alpha2: "MG",
		alpha3: "MDG",
		numeric: "450",
		dialingCode: "+261",
	},
	{
		name: "Malawi",
		alpha2: "MW",
		alpha3: "MWI",
		numeric: "454",
		dialingCode: "+265",
	},
	{
		name: "Malaysia",
		alpha2: "MY",
		alpha3: "MYS",
		numeric: "458",
		dialingCode: "+60",
	},
	{
		name: "Maldives",
		alpha2: "MV",
		alpha3: "MDV",
		numeric: "462",
		dialingCode: "+960",
	},
	{
		name: "Mali",
		alpha2: "ML",
		alpha3: "MLI",
		numeric: "466",
		dialingCode: "+223",
	},
	{
		name: "Malta",
		alpha2: "MT",
		alpha3: "MLT",
		numeric: "470",
		dialingCode: "+356",
	},
	{
		name: "Marshall Islands",
		alpha2: "MH",
		alpha3: "MHL",
		numeric: "584",
		dialingCode: "+692",
	},
	{
		name: "Martinique",
		alpha2: "MQ",
		alpha3: "MTQ",
		numeric: "474",
		dialingCode: "+596",
	},
	{
		name: "Mauritania",
		alpha2: "MR",
		alpha3: "MRT",
		numeric: "478",
		dialingCode: "+222",
	},
	{
		name: "Mauritius",
		alpha2: "MU",
		alpha3: "MUS",
		numeric: "480",
		dialingCode: "+230",
	},
	{
		name: "Mayotte",
		alpha2: "YT",
		alpha3: "MYT",
		numeric: "175",
		dialingCode: "+262",
	},
	{
		name: "Mexico",
		alpha2: "MX",
		alpha3: "MEX",
		numeric: "484",
		dialingCode: "+52",
	},
	{
		name: "Micronesia (Federated States of)",
		alpha2: "FM",
		alpha3: "FSM",
		numeric: "583",
		dialingCode: "+691",
	},
	{
		name: "Moldova (Republic of)",
		alpha2: "MD",
		alpha3: "MDA",
		numeric: "498",
		dialingCode: "+373",
	},
	{
		name: "Monaco",
		alpha2: "MC",
		alpha3: "MCO",
		numeric: "492",
		dialingCode: "+377",
	},
	{
		name: "Mongolia",
		alpha2: "MN",
		alpha3: "MNG",
		numeric: "496",
		dialingCode: "+976",
	},
	{
		name: "Montenegro",
		alpha2: "ME",
		alpha3: "MNE",
		numeric: "499",
		dialingCode: "+382",
	},
	{
		name: "Montserrat",
		alpha2: "MS",
		alpha3: "MSR",
		numeric: "500",
		dialingCode: "+1 664",
	},
	{
		name: "Morocco",
		alpha2: "MA",
		alpha3: "MAR",
		numeric: "504",
		dialingCode: "+212",
	},
	{
		name: "Mozambique",
		alpha2: "MZ",
		alpha3: "MOZ",
		numeric: "508",
		dialingCode: "+258",
	},
	{
		name: "Myanmar",
		alpha2: "MM",
		alpha3: "MMR",
		numeric: "104",
		dialingCode: "+95",
	},
	{
		name: "Namibia",
		alpha2: "NA",
		alpha3: "NAM",
		numeric: "516",
		dialingCode: "+264",
	},
	{
		name: "Nauru",
		alpha2: "NR",
		alpha3: "NRU",
		numeric: "520",
		dialingCode: "+674",
	},
	{
		name: "Nepal",
		alpha2: "NP",
		alpha3: "NPL",
		numeric: "524",
		dialingCode: "+977",
	},
	{
		name: "Netherlands",
		alpha2: "NL",
		alpha3: "NLD",
		numeric: "528",
		dialingCode: "+31",
	},
	{
		name: "New Caledonia",
		alpha2: "NC",
		alpha3: "NCL",
		numeric: "540",
		dialingCode: "+687",
	},
	{
		name: "New Zealand",
		alpha2: "NZ",
		alpha3: "NZL",
		numeric: "554",
		dialingCode: "+64",
	},
	{
		name: "Nicaragua",
		alpha2: "NI",
		alpha3: "NIC",
		numeric: "558",
		dialingCode: "+505",
	},
	{
		name: "Niger",
		alpha2: "NE",
		alpha3: "NER",
		numeric: "562",
		dialingCode: "+227",
	},
	{
		name: "Nigeria",
		alpha2: "NG",
		alpha3: "NGA",
		numeric: "566",
		dialingCode: "+234",
	},
	{
		name: "Niue",
		alpha2: "NU",
		alpha3: "NIU",
		numeric: "570",
		dialingCode: "+683",
	},
	{
		name: "Norfolk Island",
		alpha2: "NF",
		alpha3: "NFK",
		numeric: "574",
		dialingCode: "+672",
	},
	{
		name: "North Macedonia",
		alpha2: "MK",
		alpha3: "MKD",
		numeric: "807",
		dialingCode: "+389",
	},
	{
		name: "Northern Mariana Islands",
		alpha2: "MP",
		alpha3: "MNP",
		numeric: "580",
		dialingCode: "+1 670",
	},
	{
		name: "Norway",
		alpha2: "NO",
		alpha3: "NOR",
		numeric: "578",
		dialingCode: "+47",
	},
	{
		name: "Oman",
		alpha2: "OM",
		alpha3: "OMN",
		numeric: "512",
		dialingCode: "+968",
	},
	{
		name: "Pakistan",
		alpha2: "PK",
		alpha3: "PAK",
		numeric: "586",
		dialingCode: "+92",
	},
	{
		name: "Palau",
		alpha2: "PW",
		alpha3: "PLW",
		numeric: "585",
		dialingCode: "+680",
	},
	{
		name: "Palestine, State of",
		alpha2: "PS",
		alpha3: "PSE",
		numeric: "275",
		dialingCode: "+970",
	},
	{
		name: "Panama",
		alpha2: "PA",
		alpha3: "PAN",
		numeric: "591",
		dialingCode: "+507",
	},
	{
		name: "Papua New Guinea",
		alpha2: "PG",
		alpha3: "PNG",
		numeric: "598",
		dialingCode: "+675",
	},
	{
		name: "Paraguay",
		alpha2: "PY",
		alpha3: "PRY",
		numeric: "600",
		dialingCode: "+595",
	},
	{
		name: "Peru",
		alpha2: "PE",
		alpha3: "PER",
		numeric: "604",
		dialingCode: "+51",
	},
	{
		name: "Philippines",
		alpha2: "PH",
		alpha3: "PHL",
		numeric: "608",
		dialingCode: "+63",
	},
	{
		name: "Portugal",
		alpha2: "PT",
		alpha3: "PRT",
		numeric: "620",
		dialingCode: "+351",
	},
	{
		name: "Puerto Rico",
		alpha2: "PR",
		alpha3: "PRI",
		numeric: "630",
		dialingCode: "+1",
	},
	{
		name: "Qatar",
		alpha2: "QA",
		alpha3: "QAT",
		numeric: "634",
		dialingCode: "+974",
	},
	{
		name: "Réunion",
		alpha2: "RE",
		alpha3: "REU",
		numeric: "638",
		dialingCode: "+262",
	},
	{
		name: "Romania",
		alpha2: "RO",
		alpha3: "ROU",
		numeric: "642",
		dialingCode: "+40",
	},
	{
		name: "Russia",
		alpha2: "RU",
		alpha3: "RUS",
		numeric: "643",
		dialingCode: "+7",
	},
	{
		name: "Rwanda",
		alpha2: "RW",
		alpha3: "RWA",
		numeric: "646",
		dialingCode: "+250",
	},
	{
		name: "Saint Barthélemy",
		alpha2: "BL",
		alpha3: "BLM",
		numeric: "652",
		dialingCode: "+590",
	},
	{
		name: "Saint Helena, Ascension and Tristan da Cunha",
		alpha2: "SH",
		alpha3: "SHN",
		numeric: "654",
		dialingCode: "+290",
	},
	{
		name: "Saint Kitts and Nevis",
		alpha2: "KN",
		alpha3: "KNA",
		numeric: "659",
		dialingCode: "+1",
	},
	{
		name: "Saint Lucia",
		alpha2: "LC",
		alpha3: "LCA",
		numeric: "662",
		dialingCode: "+1",
	},
	{
		name: "Saint Martin (French part)",
		alpha2: "MF",
		alpha3: "MAF",
		numeric: "663",
		dialingCode: "+590",
	},
	{
		name: "Saint Pierre and Miquelon",
		alpha2: "PM",
		alpha3: "SPM",
		numeric: "666",
		dialingCode: "+508",
	},
	{
		name: "Saint Vincent and the Grenadines",
		alpha2: "VC",
		alpha3: "VCT",
		numeric: "670",
		dialingCode: "+1",
	},
	{
		name: "Samoa",
		alpha2: "WS",
		alpha3: "WSM",
		numeric: "882",
		dialingCode: "+685",
	},
	{
		name: "San Marino",
		alpha2: "SM",
		alpha3: "SMR",
		numeric: "674",
		dialingCode: "+378",
	},
	{
		name: "Sao Tome and Principe",
		alpha2: "ST",
		alpha3: "STP",
		numeric: "678",
		dialingCode: "+239",
	},
	{
		name: "Saudi Arabia",
		alpha2: "SA",
		alpha3: "SAU",
		numeric: "682",
		dialingCode: "+966",
	},
	{
		name: "Senegal",
		alpha2: "SN",
		alpha3: "SEN",
		numeric: "686",
		dialingCode: "+221",
	},
	{
		name: "Serbia",
		alpha2: "RS",
		alpha3: "SRB",
		numeric: "688",
		dialingCode: "+381",
	},
	{
		name: "Seychelles",
		alpha2: "SC",
		alpha3: "SYC",
		numeric: "690",
		dialingCode: "+248",
	},
	{
		name: "Sierra Leone",
		alpha2: "SL",
		alpha3: "SLE",
		numeric: "694",
		dialingCode: "+232",
	},
	{
		name: "Singapore",
		alpha2: "SG",
		alpha3: "SGP",
		numeric: "702",
		dialingCode: "+65",
	},
	{
		name: "Sint Maarten (Dutch part)",
		alpha2: "SX",
		alpha3: "SXM",
		numeric: "534",
		dialingCode: "+1",
	},
	{
		name: "Slovakia",
		alpha2: "SK",
		alpha3: "SVK",
		numeric: "703",
		dialingCode: "+421",
	},
	{
		name: "Slovenia",
		alpha2: "SI",
		alpha3: "SVN",
		numeric: "705",
		dialingCode: "+386",
	},
	{
		name: "Solomon Islands",
		alpha2: "SB",
		alpha3: "SLB",
		numeric: "090",
		dialingCode: "+677",
	},
	{
		name: "Somalia",
		alpha2: "SO",
		alpha3: "SOM",
		numeric: "706",
		dialingCode: "+252",
	},
	{
		name: "South Africa",
		alpha2: "ZA",
		alpha3: "ZAF",
		numeric: "710",
		dialingCode: "+27",
	},
	{
		name: "South Sudan",
		alpha2: "SS",
		alpha3: "SSD",
		numeric: "728",
		dialingCode: "+211",
	},
	{
		name: "Spain",
		alpha2: "ES",
		alpha3: "ESP",
		numeric: "724",
		dialingCode: "+34",
	},
	{
		name: "Sri Lanka",
		alpha2: "LK",
		alpha3: "LKA",
		numeric: "144",
		dialingCode: "+94",
	},
	{
		name: "Sudan",
		alpha2: "SD",
		alpha3: "SDN",
		numeric: "729",
		dialingCode: "+249",
	},
	{
		name: "Suriname",
		alpha2: "SR",
		alpha3: "SUR",
		numeric: "740",
		dialingCode: "+597",
	},
	{
		name: "Svalbard and Jan Mayen",
		alpha2: "SJ",
		alpha3: "SJM",
		numeric: "744",
		dialingCode: "+47",
	},
	{
		name: "Sweden",
		alpha2: "SE",
		alpha3: "SWE",
		numeric: "752",
		dialingCode: "+46",
	},
	{
		name: "Switzerland",
		alpha2: "CH",
		alpha3: "CHE",
		numeric: "756",
		dialingCode: "+41",
	},
	{
		name: "Syria",
		alpha2: "SY",
		alpha3: "SYR",
		numeric: "760",
		dialingCode: "+963",
	},
	{
		name: "Taiwan",
		alpha2: "TW",
		alpha3: "TWN",
		numeric: "158",
		dialingCode: "+886",
	},
	{
		name: "Tajikistan",
		alpha2: "TJ",
		alpha3: "TJK",
		numeric: "762",
		dialingCode: "+992",
	},
	{
		name: "Tanzania",
		alpha2: "TZ",
		alpha3: "TZA",
		numeric: "834",
		dialingCode: "+255",
	},
	{
		name: "Thailand",
		alpha2: "TH",
		alpha3: "THA",
		numeric: "764",
		dialingCode: "+66",
	},
	{
		name: "Timor-Leste",
		alpha2: "TL",
		alpha3: "TLS",
		numeric: "626",
		dialingCode: "+670",
	},
	{
		name: "Togo",
		alpha2: "TG",
		alpha3: "TGO",
		numeric: "768",
		dialingCode: "+228",
	},
	{
		name: "Tokelau",
		alpha2: "TK",
		alpha3: "TKL",
		numeric: "772",
		dialingCode: "+690",
	},
	{
		name: "Tonga",
		alpha2: "TO",
		alpha3: "TON",
		numeric: "776",
		dialingCode: "+676",
	},
	{
		name: "Trinidad and Tobago",
		alpha2: "TT",
		alpha3: "TTO",
		numeric: "780",
		dialingCode: "+1",
	},
	{
		name: "Tunisia",
		alpha2: "TN",
		alpha3: "TUN",
		numeric: "788",
		dialingCode: "+216",
	},
	{
		name: "Turkey",
		alpha2: "TR",
		alpha3: "TUR",
		numeric: "792",
		dialingCode: "+90",
	},
	{
		name: "Turkmenistan",
		alpha2: "TM",
		alpha3: "TKM",
		numeric: "795",
		dialingCode: "+993",
	},
	{
		name: "Turks and Caicos Islands",
		alpha2: "TC",
		alpha3: "TCA",
		numeric: "796",
		dialingCode: "+1",
	},
	{
		name: "Tuvalu",
		alpha2: "TV",
		alpha3: "TUV",
		numeric: "798",
		dialingCode: "+688",
	},
	{
		name: "Uganda",
		alpha2: "UG",
		alpha3: "UGA",
		numeric: "800",
		dialingCode: "+256",
	},
	{
		name: "Ukraine",
		alpha2: "UA",
		alpha3: "UKR",
		numeric: "804",
		dialingCode: "+380",
	},
	{
		name: "United Arab Emirates",
		alpha2: "AE",
		alpha3: "ARE",
		numeric: "784",
		dialingCode: "+971",
	},
	{
		name: "United Kingdom",
		alpha2: "GB",
		alpha3: "GBR",
		numeric: "826",
		dialingCode: "+44",
	},
	{
		name: "United States",
		alpha2: "US",
		alpha3: "USA",
		numeric: "840",
		dialingCode: "+1",
	},
	{
		name: "Uruguay",
		alpha2: "UY",
		alpha3: "URY",
		numeric: "858",
		dialingCode: "+598",
	},
	{
		name: "Uzbekistan",
		alpha2: "UZ",
		alpha3: "UZB",
		numeric: "860",
		dialingCode: "+998",
	},
	{
		name: "Vanuatu",
		alpha2: "VU",
		alpha3: "VUT",
		numeric: "548",
		dialingCode: "+678",
	},
	{
		name: "Vatican City",
		alpha2: "VA",
		alpha3: "VAT",
		numeric: "336",
		dialingCode: "+39",
	},
	{
		name: "Venezuela",
		alpha2: "VE",
		alpha3: "VEN",
		numeric: "862",
		dialingCode: "+58",
	},
	{
		name: "Vietnam",
		alpha2: "VN",
		alpha3: "VNM",
		numeric: "704",
		dialingCode: "+84",
	},
	{
		name: "Wallis and Futuna",
		alpha2: "WF",
		alpha3: "WLF",
		numeric: "876",
		dialingCode: "+681",
	},
	{
		name: "Western Sahara",
		alpha2: "EH",
		alpha3: "ESH",
		numeric: "732",
		dialingCode: "+212",
	},
	{
		name: "Yemen",
		alpha2: "YE",
		alpha3: "YEM",
		numeric: "887",
		dialingCode: "+967",
	},
	{
		name: "Zambia",
		alpha2: "ZM",
		alpha3: "ZMB",
		numeric: "894",
		dialingCode: "+260",
	},
	{
		name: "Zimbabwe",
		alpha2: "ZW",
		alpha3: "ZWE",
		numeric: "716",
		dialingCode: "+263",
	},
]
