import { Negate, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Neg = Negate("Number")
const Arg = FromArgument("Number")

// Generate an negation operation object
const config = Neg(Arg)

// Generate the composed negation function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Negate:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(1) ->", calculate(1))
console.log("calculate(-1) ->", calculate(-1))
