import {
	LogBaseTwo,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const L2 = LogBaseTwo("Number")
const Arg = FromArgument("Number")

// Generate a base two logarithm operation object
const config = L2(Arg)

// Generate the composed base two logarithm function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by LogBaseTwo:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
// 2^4 is 16
console.log(JSON.stringify(calculate(16), null, 2))
