import {
	Cotangent,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Cot = Cotangent("Number")
const Arg = FromArgument("Number")

// Generate an cotangent operation object
const config = Cot(Arg)

// Generate the composed cotangent function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Cotangent:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log(JSON.stringify(calculate(0), null, 2))
