import { Sign, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const S = Sign("Number")
const Arg = FromArgument("Number")

// Generate an sign operation object
const config = S(Arg)

// Generate the composed sign function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Sign:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log(JSON.stringify(calculate(42), null, 2))
console.log(JSON.stringify(calculate(-24), null, 2))
