import { Sign, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const S = Sign("Number")
const Arg = FromArgument("Number")

// Generate an sign operation object
const config = S(Arg)

// Generate the composed sign function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Sign:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(42) ->", calculate(42))
console.log("calculate(-24) ->", calculate(-24))
