import { ArcSine, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const ASin = ArcSine("Number")
const Arg = FromArgument("Integer")

// Generate an arcsine operation object
const config = ASin(Arg)

// Generate the composed arcsine function
const calculate = composeOperators(config)

// Show the config object and the result
if (code) {
	code.innerHTML = `The configuration generated by ArcSine:

${JSON.stringify(config, null, 2)}

Get the arcsine of 0:

calculate(0)

The return value: ${JSON.stringify(calculate(0), null, 2)}
`
}
