import {
	composeOperators,
	Constant,
	Divide,
	FromArgument,
	StandardDeviation,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Psd = StandardDeviation("Integer")(true)
const Int = Constant("Integer")

// Generate a population standard deviation operation
// from constants
const config = Psd([Int(5), Int(9), Int(7), Int(13), Int(11)])

// Generate the calculate function by passing
// the operation object to composeOperators
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by StandardDeviation:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log(JSON.stringify(), null, 2)
