import {
	ArcCosine,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const ACos = ArcCosine("Number")
const Arg = FromArgument("Integer")

// Generate an arccosine operation object
const config = ACos(Arg)

// Generate the composed arccosine function
const calculate = composeOperators(config)

// Show the config object and the result
if (code) {
	code.innerHTML = `The configuration generated by ArcCosine:

${JSON.stringify(config, null, 2)}

Get the arccosine of 1:

calculate(1)

The return value: ${JSON.stringify(calculate(1), null, 2)}
`
}
