import {
	ArcCosine,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const ACos = ArcCosine("Number")
const Arg = FromArgument("Number")

// Generate an arccosine operation object
const config = ACos(Arg)

// Generate the composed arccosine function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by ArcCosine:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(1) ->", calculate(1))
