import {
	Cosecant,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Csc = Cosecant("Number")
const Arg = FromArgument("Number")

// Generate an cosecant operation object
const config = Csc(Arg)

// Generate the composed cosecant function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Cosecant:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log(JSON.stringify(calculate(0), null, 2))
console.log(JSON.stringify(calculate(1), null, 2))
