//++ Diagnostic codes for marker adapter
export const DIAGNOSTIC = {
	EXTRA_DESCRIPTION: "COMMENT_EXTRA_DESCRIPTION",
	UNTERMINATED_BLOCK: "COMMENT_UNTERMINATED_BLOCK",
	EMPTY_TECHDEBT: "TECHDEBT_EMPTY_REASON",
	EMPTY_EXAMPLE_BLOCK: "EXAMPLE_EMPTY_BLOCK",
	AMBIGUOUS_COMMENT: "COMMENT_AMBIGUOUS_UNASSOCIATED",
} as const
