import {
	ArcTangent,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const ATan = ArcTangent("Number")
const Arg = FromArgument("Integer")

// Generate an arctangent operation object
const config = ATan(Arg)

// Generate the composed arctangent function
const calculate = composeOperators(config)

// Show the config object and the result
if (code) {
	code.innerHTML = `The configuration generated by ArcTangent:

${JSON.stringify(config, null, 2)}

Get the arctangent of 0:

calculate(0)

The return value: ${JSON.stringify(calculate(0), null, 2)}
`
}
