import {
	composeOperators,
	Constant,
	Modulo,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Mod = Modulo("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate a modulo operation from
// a constant and the passed argument
const pos = Mod(Int(7))(Arg)
const neg = Mod(Int(-7))(Arg)

// Generate the calculate function by passing
// the operation object to composeOperators
const getPos = composeOperators(pos)
const getNeg = composeOperators(neg)

// Show the pos object and the product
const out =
	"The positive configuration generated by Modulo:\n\n" +
	JSON.stringify(pos, null, 2) +
	"\n\nThe negative configuration generated by Modulo:\n\n" +
	JSON.stringify(neg, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below, then compare with remainder
// Modulo has same sign as the divisor
console.log("7 mod 3 ===", JSON.stringify(getPos(3), null, 2))
console.log("7 mod -3 ===", JSON.stringify(getPos(-3), null, 2))
console.log("-7 mod 3 ===", JSON.stringify(getNeg(3), null, 2))
console.log("-7 mod -3 ===", JSON.stringify(getNeg(-3), null, 2))
