import {
	composeOperators,
	Constant,
	Modulo,
	FromArgument,
	Multiply,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Product = Multiply("Integer")
const Mod = Modulo("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate a modulo operation with nested multiplication
// from constants and the passed argument
const config = Mod(Product([Int(21), Int(2), Int(2)]))(Arg)

// Generate the calculate function by passing
// the operation object to composeOperators
const calculate = composeOperators(config)

// Show the config object and the product
const out =
	"The configuration generated by Modulo:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(5) ->", calculate(-5))
