export type ScaffoldOptions = {
	name: string
	template?: "mission-control" | "the-workshop"
	targetDir?: string
}

export async function scaffoldApp(opts: ScaffoldOptions): Promise<void> {
	const { name, template = "mission-control", targetDir = `./${name}` } = opts
	const resolved = new URL(targetDir, new URL(".", import.meta.url)).pathname
	await Deno.mkdir(resolved, { recursive: true })

	// Minimal files; later extend with real templates
	await Deno.writeTextFile(
		`${resolved}/README.md`,
		`# ${name}\n\nGenerated by Sitebender scaffold.`,
	)

	if (template === "mission-control") {
		await Deno.writeTextFile(
			`${resolved}/deno.jsonc`,
			`{
  "tasks": {"dev": "deno task --cwd ../../applications/mission-control dev"}
}`,
		)
	} else if (template === "the-workshop") {
		await Deno.writeTextFile(
			`${resolved}/deno.jsonc`,
			`{
  "tasks": {"dev": "deno task --cwd ../../applications/the-workshop dev"}
}`,
		)
	}
}
