import {
	Median,
	composeOperators,
	Constant,
	Divide,
	FromArgument,
	Multiply,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Mdn = Median("Number")
const Quotient = Divide("Integer")
const Product = Multiply("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate an addition with nested division
// from constants and the passed argument
const config = Mdn([
	Quotient(Int(14))(Int(2)),
	Int(5),
	Int(13),
	Product([Int(3), Int(3)]),
	Int(3),
	Arg,
])

// Generate the calculate function by passing
// the operation object to composeOperators
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Median:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log(JSON.stringify(calculate(11), null, 2))
