import { Cosine, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Cos = Cosine("Number")
const Arg = FromArgument("Number")

// Generate an cosine operation object
const config = Cos(Arg)

// Generate the composed cosine function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Cosine:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(0) ->", calculate(0))
