import { Ceiling, composeOperators, FromArgument } from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Ceil2 = Ceiling("Number")(2)
const Arg = FromArgument("Number")

// Generate an ceiling operation object
const config = Ceil2(Arg)

// Generate the composed ceiling function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Ceiling:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(11.223344) ->", calculate(11.223344))
// Ceiling is toward Infinity
console.log("calculate(-11.223344) ->", calculate(-11.223344))
