import {
	ArcHyperbolicTangent,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const AHTan = ArcHyperbolicTangent("Number")
const Arg = FromArgument("Number")

// Generate an atanh operation object
const config = AHTan(Arg)

// Generate the composed atanh function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by ArcHyperbolicTangent:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("calculate(0) ->", calculate(0))
