import {
	ArcHyperbolicTangent,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const AHTan = ArcHyperbolicTangent("Number")
const Arg = FromArgument("Integer")

// Generate an atanh operation object
const config = AHTan(Arg)

// Generate the composed atanh function
const calculate = composeOperators(config)

// Show the config object and the result
if (code) {
	code.innerHTML = `The configuration generated by ArcHyperbolicTangent:

${JSON.stringify(config, null, 2)}

Get the atanh of 0:

calculate(0)

The return value: ${JSON.stringify(calculate(0), null, 2)}
`
}
