apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

# Provision Thanos Querier as the default Prometheus-compatible datasource
# Grafana will talk to Thanos, which federates Prometheus + MinIO blocks

datasources:
  - name: Thanos
    type: prometheus
    access: proxy
    url: http://thanos-querier:10902
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
      # Optional: set HTTP method
      httpMethod: POST
      # Optional: enable prometheus query features
      prometheusVersion: 2.47.0
      # Optional: disable scrape interval warning
      manageAlerts: false
    version: 1
    editable: true
