apiVersion: 1

# Auto-provision a Thanos Querier datasource so Grafana works out of the box
# http://localhost:10902 is exposed by the thanos-querier service in docker-compose

deleteDatasources:
  - name: Thanos
    orgId: 1

datasources:
  - name: Thanos
    type: prometheus
    access: proxy
    url: http://thanos-querier:10902
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
      prometheusType: Thanos
      # Enable exemplar support if you add tracing later
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
    editable: false
