import {
	composeOperators,
	Constant,
	Divide,
	FromArgument,
	Multiply,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Product = Multiply("Integer")
const Quotient = Divide("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate an addition with nested division
// from constants and the passed argument
const config = Product([Quotient(Int(84))(Int(4)), Int(1), Arg])

// Run the calculation returning Either<Error, Integer>
const calculate = composeOperators(config)

// Show the config object and the sum
if (code) {
	code.innerHTML = `The configuration generated by Multiply:

${JSON.stringify(config, null, 2)}

Calculate (84 / 4) * 1 * 2:

calculate(2)

The return value: ${JSON.stringify(calculate(2), null, 2)}
`
}
