import {
	composeOperators,
	Constant,
	Remainder,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Rem = Remainder("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate a modulo operation from
// a constant and the passed argument
const pos = Rem(Int(7))(Arg)
const neg = Rem(Int(-7))(Arg)

// Generate the calculate function by passing
// the operation object to composeOperators
const getPos = composeOperators(pos)
const getNeg = composeOperators(neg)

// Show the pos object and the product
const out =
	"The positive configuration generated by Remainder:\n\n" +
	JSON.stringify(pos, null, 2) +
	"\n\nThe negative configuration generated by Remainder:\n\n" +
	JSON.stringify(neg, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below, then compare with modulo
// Remainder has same sign as the dividend
console.log("7 % 3 ===", JSON.stringify(getPos(3), null, 2))
console.log("7 % -3 ===", JSON.stringify(getPos(-3), null, 2))
console.log("-7 % 3 ===", JSON.stringify(getNeg(3), null, 2))
console.log("-7 % -3 ===", JSON.stringify(getNeg(-3), null, 2))
