import {
	Hypotenuse,
	composeOperators,
	Constant,
	Divide,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Hypot = Hypotenuse("Number")
const Quotient = Divide("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate a hypotenuse with nested division
// from constants and the passed argument
const config = Hypot([Quotient(Int(6))(Int(2)), Arg])

// Generate the calculate function by passing
// the operation object to composeOperators
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by Hypotenuse:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
// 3-4-5 right triangle
console.log("calculate(4) ->", calculate(4))
