import {
	composeOperators,
	Constant,
	Divide,
	FromArgument,
	Multiply,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Product = Multiply("Integer")
const Quotient = Divide("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate a division with nested multiplication
// from constants and the passed argument
const config = Quotient(Product([Int(21), Int(2), Int(2)]))(Arg)

// Generate the calculate function by passing
// the operation object to composeOperators
const calculate = composeOperators(config)

// Show the config object and the product
const out =
	"The configuration generated by Divide:\n\n" + JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log("divide by 2 ===", JSON.stringify(calculate(2), null, 2))
console.log("divide by 0 ===", JSON.stringify(calculate(0), null, 2))
