import {
	composeOperators,
	Constant,
	Divide,
	FromArgument,
	Multiply,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Product = Multiply("Integer")
const Quotient = Divide("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate a division with nested multiplication
// from constants and the passed argument
const config = Quotient(Product([Int(21), Int(2), Int(2)]))(Arg)

// Run the calculation returning Either<Error, Integer>
const calculate = composeOperators(config)

// Show the config object and the product
if (code) {
	code.innerHTML = `The configuration generated by Multiply:

${JSON.stringify(config, null, 2)}

Calculate (21 * 2 * 2) / 2:

calculate(2)

The return value: ${JSON.stringify(calculate(2), null, 2)}
`
}
