/*++
 + Global attribute names (always allowed)
 */
export const GLOBAL_ATTRIBUTES = [
	"accesskey",
	"autocapitalize",
	"class",
	"contenteditable",
	"dir",
	"draggable",
	"enterkeyhint",
	"exportparts",
	"hidden",
	"id",
	"inert",
	"inputmode",
	"is",
	"itemid",
	"itemprop",
	"itemref",
	"itemscope",
	"itemtype",
	"lang",
	"nonce",
	"part",
	"popover",
	"slot",
	"spellcheck",
	"style",
	"tabindex",
	"title",
	"translate",
	"virtualkeyboardpolicy",
] as const

/*++
 + HTML elements PERMITTED in the <head>
 + Some of these (meta, script, noscript) may also appear in <body>
 */
export const HEAD_ELEMENTS = [
	"BASE",
	"LINK",
	"META",
	"NOSCRIPT",
	"SCRIPT",
	"STYLE",
	"TEMPLATE",
	"TITLE",
] as const

/*++
 + Valid attributes for the <html> element (excluding global attributes)
 */
export const VALID_HTML_ATTRIBUTES = ["dir", "lang", "xmlns"] as const

/*++
 + Valid values for global attribute enums
 */
export const ENUMERATED_ATTRIBUTE_VALUES = {
	autocapitalize: [
		"off",
		"none",
		"on",
		"sentences",
		"words",
		"characters",
	] as const,
	contenteditable: [
		"true",
		"false",
		"plaintext-only",
		"",
	] as const,
	dir: ["auto", "ltr", "rtl"] as const,
	draggable: ["true", "false"] as const,
	enterkeyhint: [
		"enter",
		"done",
		"go",
		"next",
		"previous",
		"search",
		"send",
	] as const,
	hidden: ["", "until-found"] as const,
	inert: [""] as const,
	inputmode: [
		"none",
		"text",
		"decimal",
		"numeric",
		"tel",
		"search",
		"email",
		"url",
	] as const,
	popover: ["", "auto", "manual"] as const,
	virtualkeyboardpolicy: ["auto", "manual"] as const,
} as const

/*++
 + Permitted ARIA roles by HTML element
 + Source: https://w3c.github.io/html-aria/
 + Last updated: 2025-11-04 (based on July 2025 spec)
 +
 + Values:
 + - "none": No role attribute allowed
 + - "any": Any valid ARIA role allowed
 + - ReadonlyArray<string>: Specific permitted roles
 +
 + Notes:
 + - Conditional elements use permissive arrays (validation refined in components)
 + - Tree-level lint handles ancestor-dependent rules
 */
export const ROLES_BY_ELEMENT: Readonly<
	Record<string, "none" | "any" | ReadonlyArray<string>>
> = {
	// ========================================
	// "none" - No role allowed (20 elements)
	// ========================================
	base: "none",
	col: "none",
	colgroup: "none",
	datalist: "none",
	dd: "none",
	head: "none",
	legend: "none",
	link: "none",
	map: "none",
	meta: "none",
	noscript: "none",
	param: "none",
	picture: "none",
	script: "none",
	slot: "none",
	source: "none",
	style: "none",
	template: "none",
	title: "none",
	track: "none",

	// ========================================
	// "any" - Any role allowed (35 elements)
	// ========================================
	abbr: "any",
	address: "any",
	b: "any",
	bdi: "any",
	bdo: "any",
	blockquote: "any",
	canvas: "any",
	cite: "any",
	code: "any",
	data: "any",
	del: "any",
	dfn: "any",
	div: "any",
	em: "any",
	figure: "any",
	hgroup: "any",
	i: "any",
	ins: "any",
	kbd: "any",
	label: "any",
	li: "any",
	mark: "any",
	output: "any",
	p: "any",
	pre: "any",
	q: "any",
	rp: "any",
	rt: "any",
	ruby: "any",
	s: "any",
	samp: "any",
	small: "any",
	span: "any",
	strong: "any",
	sub: "any",
	summary: "any",
	sup: "any",
	svg: "any",
	table: "any",
	tbody: "any",
	td: "any",
	tfoot: "any",
	th: "any",
	thead: "any",
	time: "any",
	tr: "any",
	u: "any",
	var: "any",
	wbr: "any",

	// ========================================
	// Specific role arrays (60+ elements)
	// ========================================

	// Document structure
	body: ["generic"],
	html: ["document", "generic"],

	// Sectioning
	article: [
		"application",
		"document",
		"feed",
		"main",
		"none",
		"presentation",
		"region",
	],
	aside: [
		"doc-dedication",
		"doc-example",
		"doc-footnote",
		"doc-glossary",
		"doc-pullquote",
		"doc-tip",
		"feed",
		"none",
		"note",
		"presentation",
		"region",
		"search",
	],
	footer: [
		"contentinfo",
		"doc-footnote",
		"group",
		"none",
		"presentation",
	],
	header: ["banner", "group", "none", "presentation"],
	main: ["main"],
	nav: [
		"doc-index",
		"doc-pagelist",
		"doc-toc",
		"menu",
		"menubar",
		"none",
		"presentation",
		"tablist",
	],
	section: [
		"alert",
		"alertdialog",
		"application",
		"banner",
		"complementary",
		"contentinfo",
		"dialog",
		"doc-abstract",
		"doc-acknowledgments",
		"doc-afterword",
		"doc-appendix",
		"doc-bibliography",
		"doc-chapter",
		"doc-colophon",
		"doc-conclusion",
		"doc-credit",
		"doc-credits",
		"doc-dedication",
		"doc-endnotes",
		"doc-epigraph",
		"doc-epilogue",
		"doc-errata",
		"doc-example",
		"doc-foreword",
		"doc-glossary",
		"doc-index",
		"doc-introduction",
		"doc-notice",
		"doc-pagelist",
		"doc-part",
		"doc-preface",
		"doc-prologue",
		"doc-pullquote",
		"doc-qna",
		"doc-toc",
		"document",
		"feed",
		"group",
		"log",
		"main",
		"marquee",
		"navigation",
		"none",
		"note",
		"presentation",
		"region",
		"search",
		"status",
		"tabpanel",
	],

	// Grouping
	dialog: ["alertdialog", "dialog"],
	dl: ["group", "list", "none", "presentation"],
	dt: ["listitem"],
	fieldset: ["none", "presentation", "radiogroup"],
	figcaption: ["group", "none", "presentation"],
	form: ["none", "presentation", "search"],
	hr: ["doc-pagebreak", "none", "presentation"],
	menu: [
		"group",
		"listbox",
		"menu",
		"menubar",
		"none",
		"presentation",
		"radiogroup",
		"tablist",
		"toolbar",
		"tree",
	],
	ol: [
		"group",
		"listbox",
		"menu",
		"menubar",
		"none",
		"presentation",
		"radiogroup",
		"tablist",
		"toolbar",
		"tree",
	],
	search: ["form", "group", "none", "presentation", "region"],
	ul: [
		"group",
		"listbox",
		"menu",
		"menubar",
		"none",
		"presentation",
		"radiogroup",
		"tablist",
		"toolbar",
		"tree",
	],

	// Headings
	h1: ["doc-subtitle", "none", "presentation", "tab"],
	h2: ["doc-subtitle", "none", "presentation", "tab"],
	h3: ["doc-subtitle", "none", "presentation", "tab"],
	h4: ["doc-subtitle", "none", "presentation", "tab"],
	h5: ["doc-subtitle", "none", "presentation", "tab"],
	h6: ["doc-subtitle", "none", "presentation", "tab"],

	// Text
	br: ["none", "presentation"],

	// Embedded
	area: ["button", "generic", "link"],
	audio: ["application"],
	embed: ["application", "document", "img", "image", "none", "presentation"],
	iframe: [
		"application",
		"document",
		"img",
		"image",
		"none",
		"presentation",
	],
	img: [
		"button",
		"checkbox",
		"doc-cover",
		"link",
		"math",
		"menuitem",
		"menuitemcheckbox",
		"menuitemradio",
		"meter",
		"none",
		"option",
		"presentation",
		"progressbar",
		"radio",
		"scrollbar",
		"separator",
		"slider",
		"switch",
		"tab",
		"treeitem",
	],
	math: ["math"],
	object: ["application", "document", "img", "image"],
	video: ["application"],

	// Tables
	caption: ["caption"],

	// Forms
	a: [
		"button",
		"checkbox",
		"doc-backlink",
		"doc-biblioref",
		"doc-glossref",
		"doc-noteref",
		"menuitem",
		"menuitemcheckbox",
		"menuitemradio",
		"option",
		"radio",
		"switch",
		"tab",
		"treeitem",
	],
	button: [
		"checkbox",
		"combobox",
		"gridcell",
		"link",
		"menuitem",
		"menuitemcheckbox",
		"menuitemradio",
		"option",
		"radio",
		"separator",
		"slider",
		"switch",
		"tab",
		"treeitem",
	],
	details: ["group"],
	input: [
		"button",
		"checkbox",
		"combobox",
		"gridcell",
		"link",
		"menuitem",
		"menuitemcheckbox",
		"menuitemradio",
		"option",
		"radio",
		"searchbox",
		"separator",
		"slider",
		"spinbutton",
		"switch",
		"tab",
		"textbox",
		"treeitem",
	],
	meter: ["meter"],
	optgroup: ["group"],
	option: ["option"],
	progress: ["progressbar"],
	select: ["combobox", "listbox", "menu"],
	textarea: ["textbox"],
} as const

/*++
 + Element-specific attribute names (non-global attributes per element)
 + First pass - basic elements only
 */
export const ELEMENT_SPECIFIC_ATTRIBUTES: Readonly<Record<string, ReadonlyArray<string>>> = {
	html: ["xmlns"],
	a: ["href", "target", "download", "ping", "rel", "hreflang", "type", "referrerpolicy"],
	area: ["alt", "coords", "shape", "href", "target", "download", "ping", "rel", "referrerpolicy"],
	audio: ["src", "crossorigin", "preload", "autoplay", "loop", "muted", "controls"],
	button: ["autofocus", "disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "name", "type", "value"],
	form: ["accept-charset", "action", "autocomplete", "enctype", "method", "name", "novalidate", "rel", "target"],
	img: ["alt", "src", "srcset", "sizes", "crossorigin", "usemap", "ismap", "width", "height", "referrerpolicy", "decoding", "loading", "fetchpriority"],
	input: ["accept", "alt", "autocomplete", "checked", "dirname", "disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "height", "list", "max", "maxlength", "min", "minlength", "multiple", "name", "pattern", "placeholder", "readonly", "required", "size", "src", "step", "type", "value", "width"],
	link: ["href", "crossorigin", "rel", "media", "hreflang", "type", "sizes", "imagesrcset", "imagesizes", "referrerpolicy", "integrity", "blocking", "color", "disabled", "fetchpriority"],
	meta: ["name", "http-equiv", "content", "charset", "media"],
	script: ["src", "type", "nomodule", "async", "defer", "crossorigin", "integrity", "referrerpolicy", "blocking", "fetchpriority"],
	select: ["autocomplete", "disabled", "form", "multiple", "name", "required", "size"],
	textarea: ["autocomplete", "cols", "dirname", "disabled", "form", "maxlength", "minlength", "name", "placeholder", "readonly", "required", "rows", "wrap"],
	video: ["src", "crossorigin", "poster", "preload", "autoplay", "playsinline", "loop", "muted", "controls", "width", "height"],
} as const
