import {
	HyperbolicTangent,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const HTan = HyperbolicTangent("Number")
const Arg = FromArgument("Number")

// Generate an tanh operation object
const config = HTan(Arg)

// Generate the composed tanh function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by HyperbolicTangent:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
console.log(JSON.stringify(calculate(1), null, 2))
