import {
	Average,
	composeOperators,
	Constant,
	Divide,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Avg = Average("Integer")
const Quotient = Divide("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate an addition with nested division
// from constants and the passed argument
const config = Avg([Quotient(Int(20))(Int(2)), Int(11), Arg])

// Generate the calculate function by passing
// the operation object to composeOperators
const calculate = composeOperators(config)

// Show the config object and the sum
if (code) {
	code.innerHTML = `The configuration generated by Average:

${JSON.stringify(config, null, 2)}

Calculate ((20 / 2) + 11 + 21) / 3:

calculate(21)

The return value: ${JSON.stringify(calculate(21), null, 2)}
`
}
