[package]
name = "webtransport-server"
version = "0.1.0"
edition = "2021"

[dependencies]
wtransport = "0.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
mime_guess = "2"
notify = "6"
bytes = "1"
http = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
