#!/usr/bin/env -S deno run --allow-read --allow-write

//++ Generates human-readable rules markdown files from rules JSON files throughout the project

import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, "..", "..")

interface RulesFile {
	path: string
	jsonPath: string
	mdPath: string
}

//++ Finds all rules/index.json files in the project
function findRulesFiles(dir: string = projectRoot): Array<RulesFile> {
	const rulesFiles: Array<RulesFile> = []

	// Check common locations for rules files
	const locations = [
		"rules/index.json",
		"applications/rules/index.json",
		"libraries/components/rules/index.json",
		"libraries/engine/rules/index.json",
		"libraries/toolkit/rules/index.json",
		"libraries/foundry/rules/index.json",
		"libraries/prover/rules/index.json",
		"libraries/envoy/rules/index.json",
		"libraries/parser/rules/index.json",
		"libraries/maths/rules/index.json",
		"libraries/mesh/rules/index.json",
	]

	for (const location of locations) {
		const fullPath = join(projectRoot, location)
		if (existsSync(fullPath)) {
			rulesFiles.push({
				path: dirname(fullPath),
				jsonPath: fullPath,
				mdPath: fullPath.replace(".json", ".md"),
			})
		}
	}

	return rulesFiles
}

//++ Generates markdown for a single rules file
function generateMarkdownForRules(rulesFile: RulesFile): void {
	const rulesContent = readFileSync(rulesFile.jsonPath, "utf-8")
	const rules = JSON.parse(rulesContent)
	const relativePath = relative(projectRoot, rulesFile.jsonPath)

	const sections: Array<string> = []

	// Header
	const title = rules.scope ? `${rules.scope} Rules` : "Project Rules"
	sections.push(`# ${title}

> **GENERATED FILE - DO NOT EDIT**
> 
> This file is automatically generated from \`${relativePath}\`.
> To make changes, edit the JSON file and run \`deno task generate-rules\`.

**Version**: ${rules.version}  
**Last Updated**: ${rules.lastUpdated}  
**Author**: ${rules.author}`)

	if (rules.description) {
		sections.push(`\n**Description**: ${rules.description}`)
	}

	if (rules.inherits) {
		sections.push(`\n**Inherits from**: \`${rules.inherits}\``)
	}

	// Table of Contents (only for sections that exist)
	const toc: Array<string> = []
	let tocIndex = 1

	if (rules.primeDirective) {
		toc.push(`${tocIndex++}. [The Prime Directive](#the-prime-directive)`)
	}
	if (rules.commandments) {
		toc.push(`${tocIndex++}. [Commandments](#commandments)`)
	}
	if (rules.libraryRulesApplication) {
		toc.push(
			`${tocIndex++}. [Library Rules Application](#library-rules-application)`,
		)
	}
	if (rules.progressiveEnhancement) {
		toc.push(
			`${tocIndex++}. [Progressive Enhancement](#progressive-enhancement)`,
		)
	}
	if (rules.browserRequirements) {
		toc.push(`${tocIndex++}. [Browser Requirements](#browser-requirements)`)
	}
	if (rules.codeOrganization) {
		toc.push(`${tocIndex++}. [Code Organization](#code-organization)`)
	}
	if (rules.functionalProgramming) {
		toc.push(`${tocIndex++}. [Functional Programming](#functional-programming)`)
	}
	if (rules.imports) toc.push(`${tocIndex++}. [Import Rules](#import-rules)`)
	if (rules.testing) {
		toc.push(`${tocIndex++}. [Testing Requirements](#testing-requirements)`)
	}
	if (rules.sevenDeadlySins) {
		toc.push(`${tocIndex++}. [The Seven Deadly Sins](#the-seven-deadly-sins)`)
	}
	if (rules.errorHandling) {
		toc.push(`${tocIndex++}. [Error Handling](#error-handling)`)
	}
	if (rules.dataPrivacy) {
		toc.push(`${tocIndex++}. [Data Privacy](#data-privacy)`)
	}
	if (rules.git) toc.push(`${tocIndex++}. [Git Workflow](#git-workflow)`)
	if (rules.codeStyle) toc.push(`${tocIndex++}. [Code Style](#code-style)`)
	if (rules.envoyComments) {
		toc.push(`${tocIndex++}. [Envoy Comments](#envoy-comments)`)
	}
	if (rules.responsiveDesign) {
		toc.push(`${tocIndex++}. [Responsive Design](#responsive-design)`)
	}
	if (rules.engineSpecific) {
		toc.push(`${tocIndex++}. [Engine Specific](#engine-specific)`)
	}
	if (rules.cognitiveLoad) {
		toc.push(`${tocIndex++}. [Cognitive Load](#cognitive-load)`)
	}
	if (rules.sacredOath) {
		toc.push(`${tocIndex++}. [The Sacred Oath](#the-sacred-oath)`)
	}
	if (rules.finalWarnings) {
		toc.push(`${tocIndex++}. [Final Warnings](#final-warnings)`)
	}

	if (toc.length > 0) {
		sections.push(`\n## Table of Contents\n\n${toc.join("\n")}`)
	}

	// Prime Directive
	if (rules.primeDirective) {
		sections.push(`
## The Prime Directive

### ${rules.primeDirective.rule}

${rules.primeDirective.description}

${rules.primeDirective.rationale}

### The Cost of Your Assumptions

${rules.primeDirective.costs.map((cost: string) => `- **${cost}**`).join("\n")}

${rules.primeDirective.enforcement}`)
	}

	// Commandments
	if (rules.commandments) {
		sections.push(`
## Commandments

${
			rules.commandments.map((cmd: any) =>
				`### ${cmd.key ? `[${cmd.key}]` : ""} ${cmd.title}

${cmd.details.map((detail: string) => `- ${detail}`).join("\n")}`
			).join("\n\n")
		}`)
	}

	// Library Rules Application
	if (rules.libraryRulesApplication) {
		sections.push(`
## Library Rules Application

${rules.libraryRulesApplication.note}

${rules.libraryRulesApplication.clarification || ""}

### Required Library Rules
${
			rules.libraryRulesApplication.requiredLibraryRules.map((rule: string) =>
				`- \`${rule}\``
			).join("\n")
		}`)
	}

	// Progressive Enhancement
	if (rules.progressiveEnhancement) {
		sections.push(`
## Progressive Enhancement`)

		if (rules.progressiveEnhancement.layers) {
			sections.push(`
### The Three Layers

${
				rules.progressiveEnhancement.layers.map((layer: any) =>
					`#### Layer ${layer.level}: ${layer.name}
- **Description**: ${layer.description}
- **Requirement**: ${layer.requirement}`
				).join("\n\n")
			}`)
		}

		if (rules.progressiveEnhancement.unbreakableRules) {
			sections.push(`
### Unbreakable Rules

${
				rules.progressiveEnhancement.unbreakableRules.map((rule: any) =>
					`#### ${rule.rule}
${rule.details.map((detail: string) => `- ${detail}`).join("\n")}`
				).join("\n\n")
			}`)
		}

		if (rules.progressiveEnhancement.componentRequirements) {
			sections.push(`
### Component Requirements

${
				rules.progressiveEnhancement.componentRequirements.map((req: string) =>
					`- ${req}`
				).join("\n")
			}`)
		}
	}

	// Browser Requirements
	if (rules.browserRequirements) {
		sections.push(`
## Browser Requirements

${rules.browserRequirements.description || ""}`)

		if (rules.browserRequirements.layers) {
			sections.push(`
### The Three Layers

${
				rules.browserRequirements.layers.map((layer: any) =>
					`#### Layer ${layer.level}: ${layer.name}
- **Description**: ${layer.description}
- **Requirement**: ${layer.requirement}`
				).join("\n\n")
			}`)
		}

		if (rules.browserRequirements.unbreakableRules) {
			sections.push(`
### Unbreakable Rules

${
				rules.browserRequirements.unbreakableRules.map((rule: any) =>
					`#### ${rule.rule}
${rule.details.map((detail: string) => `- ${detail}`).join("\n")}`
				).join("\n\n")
			}`)
		}
	}

	// Code Organization
	if (rules.codeOrganization) {
		sections.push(`
## Code Organization`)

		if (rules.codeOrganization.laws) {
			sections.push(`
### The Immutable Laws

${
				rules.codeOrganization.laws.map((law: any) =>
					`#### Law ${law.id}: ${law.name}

**Requirement**: ${law.requirement}

${
						law.example
							? `**Example**:
- ✅ Correct: \`${law.example.correct}\`
- ❌ Incorrect: ${law.example.incorrect}`
							: ""
					}

${
						law.benefits
							? `**Benefits**:
${law.benefits.map((benefit: string) => `- ${benefit}`).join("\n")}`
							: ""
					}

${
						law.exceptions
							? `**Exceptions**:
${law.exceptions.map((exception: string) => `- ${exception}`).join("\n")}`
							: ""
					}

${law.rule || ""}`
				).join("\n\n")
			}`)
		}

		if (rules.codeOrganization.naming) {
			sections.push(`
### Naming Conventions

- **Functions**: ${rules.codeOrganization.naming.functions}
- **Types**: ${rules.codeOrganization.naming.types}
- **Constants**: ${rules.codeOrganization.naming.constants}
- **Routes**: ${rules.codeOrganization.naming.routes}

**Forbidden**:
${
				rules.codeOrganization.naming.forbidden.map((item: string) =>
					`- ${item}`
				).join("\n")
			}`)
		}

		if (rules.codeOrganization.barrelFiles) {
			sections.push(`
### Barrel Files

**${rules.codeOrganization.barrelFiles}**`)
		}
	}

	// Functional Programming
	if (rules.functionalProgramming) {
		sections.push(`
## Functional Programming`)

		if (rules.functionalProgramming.transitionProphecy) {
			sections.push(`
### The Transition Prophecy

We're transitioning from **${rules.functionalProgramming.transitionProphecy.from}** to **${rules.functionalProgramming.transitionProphecy.to}**.

**Why?**
${
				rules.functionalProgramming.transitionProphecy.rationale.map((
					reason: string,
				) => `- ${reason}`).join("\n")
			}`)
		}

		if (rules.functionalProgramming.required) {
			sections.push(`
### Required Practices

${
				rules.functionalProgramming.required.map((req: string) => `- ${req}`)
					.join("\n")
			}`)
		}

		if (rules.functionalProgramming.forbidden) {
			sections.push(`
### Forbidden Practices

${
				rules.functionalProgramming.forbidden.map((forbidden: string) =>
					`- ${forbidden}`
				).join("\n")
			}`)
		}
	}

	// Import Rules
	if (rules.imports) {
		sections.push(`
## Import Rules`)

		if (rules.imports.externalDependencies) {
			sections.push(`
### External Dependencies

**Rule**: ${rules.imports.externalDependencies.rule}

- **Parser**: ${rules.imports.externalDependencies.parser}
- **Mesh**: ${rules.imports.externalDependencies.mesh}
- **All Others**: ${rules.imports.externalDependencies.allOthers}`)
		}

		if (rules.imports.realms) {
			sections.push(`
### The Three Realms

#### Library Code
- **Internal imports**: ${rules.imports.realms.libraries.internal}
- **Other libraries**: ${rules.imports.realms.libraries.otherLibraries}
- **External deps**: ${rules.imports.realms.libraries.external}

#### Application Code
- **Internal imports**: ${rules.imports.realms.applications.internal}
- **Libraries**: ${rules.imports.realms.applications.libraries}
- **External deps**: ${rules.imports.realms.applications.external}

#### Test Code
- **Tested code**: ${rules.imports.realms.tests.testedCode}
- **Test deps**: ${rules.imports.realms.tests.testDeps}`)
		}

		if (rules.imports.commandments) {
			sections.push(`
### Import Commandments

${rules.imports.commandments.map((cmd: string) => `- ${cmd}`).join("\n")}`)
		}
	}

	// Responsive Design
	if (rules.responsiveDesign) {
		sections.push(`
## Responsive Design`)

		if (rules.responsiveDesign.requirements) {
			sections.push(`
### Requirements

${
				rules.responsiveDesign.requirements.map((req: string) => `- ${req}`)
					.join("\n")
			}`)
		}
	}

	// Engine Specific
	if (rules.engineSpecific) {
		sections.push(`
## Engine Specific`)

		if (rules.engineSpecific.irEvaluation) {
			sections.push(`
### IR Evaluation

${
				rules.engineSpecific.irEvaluation.map((item: string) => `- ${item}`)
					.join("\n")
			}`)
		}

		if (rules.engineSpecific.responsiveOutput) {
			sections.push(`
### Responsive Output

${
				rules.engineSpecific.responsiveOutput.map((item: string) => `- ${item}`)
					.join("\n")
			}`)
		}
	}

	// Testing
	if (rules.testing) {
		sections.push(`
## Testing Requirements`)

		if (rules.testing.coverage) {
			sections.push(`
### Coverage

**${rules.testing.coverage.requirement}**

${rules.testing.coverage.rationale}

Escape clause: ${rules.testing.coverage.escape}`)
		}

		if (rules.testing.hierarchy) {
			sections.push(`
### Testing Hierarchy

${
				rules.testing.hierarchy.map((level: string, index: number) =>
					`${index + 1}. **${level}**`
				).join("\n")
			}`)
		}

		if (rules.testing.whatToTest) {
			sections.push(`
### What to Test

${rules.testing.whatToTest.map((item: string) => `- ${item}`).join("\n")}`)
		}

		if (rules.testing.whatNotToTest) {
			sections.push(`
### What NOT to Test

${rules.testing.whatNotToTest.map((item: string) => `- ${item}`).join("\n")}`)
		}

		if (rules.testing.location) {
			sections.push(`
### Test Location

${rules.testing.location}`)
		}
	}

	// Seven Deadly Sins
	if (rules.sevenDeadlySins) {
		sections.push(`
## The Seven Deadly Sins

${
			rules.sevenDeadlySins.map((sin: any, index: number) =>
				`### ${index + 1}. ${sin.sin}${
					sin.description ? ` - ${sin.description}` : ""
				}

**Examples of the sin**:
${sin.examples.map((ex: string) => `- ❌ ${ex}`).join("\n")}

**Solution**: ${sin.solution}`
			).join("\n\n")
		}`)
	}

	// Error Handling
	if (rules.errorHandling) {
		sections.push(`
## Error Handling`)

		if (rules.errorHandling.laws) {
			sections.push(`
### The Laws of Error Handling

${
				rules.errorHandling.laws.map((law: any) =>
					`#### Law ${law.id}: ${law.law}

${
						law.details
							? law.details.map((detail: string) => `- ${detail}`).join("\n")
							: ""
					}

${
						law.example
							? `**Example**:
- ✅ Correct: \`${law.example.correct}\`
- ❌ Incorrect: \`${law.example.incorrect}\``
							: ""
					}`
				).join("\n\n")
			}`)
		}

		if (rules.errorHandling.recoveryStrategies) {
			sections.push(`
### Recovery Strategies

${
				rules.errorHandling.recoveryStrategies.map((strategy: string) =>
					`- ${strategy}`
				).join("\n")
			}`)
		}
	}

	// Data Privacy
	if (rules.dataPrivacy) {
		sections.push(`
## Data Privacy`)

		if (rules.dataPrivacy.localFirst) {
			sections.push(`
### Local-First Principles

${
				rules.dataPrivacy.localFirst.map((principle: any) =>
					`#### ${principle.principle}

${principle.details.map((detail: string) => `- ${detail}`).join("\n")}`
				).join("\n\n")
			}`)
		}
	}

	// Git Workflow
	if (rules.git) {
		sections.push(`
## Git Workflow`)

		if (rules.git.conventionalCommits) {
			sections.push(`
### Conventional Commits

**Required**: ${rules.git.conventionalCommits.required ? "Yes" : "No"}  
**Format**: \`${rules.git.conventionalCommits.format}\`  
**Types**: ${rules.git.conventionalCommits.types.join(", ")}`)
		}

		if (rules.git.commitRules) {
			sections.push(`
### Commit Rules

${rules.git.commitRules.map((rule: string) => `- ${rule}`).join("\n")}`)
		}

		if (rules.git.preCommitRequirements) {
			sections.push(`
### Pre-Commit Requirements

${
				rules.git.preCommitRequirements.map((req: string) => `- \`${req}\``)
					.join("\n")
			}

**${rules.git.enforcement}**`)
		}

		if (rules.git.aiAssistants) {
			sections.push(`
### For AI Assistants

${rules.git.aiAssistants.note}

**Requirements**:
${
				rules.git.aiAssistants.requirements.map((req: string) => `- ${req}`)
					.join("\n")
			}`)
		}
	}

	// Code Style
	if (rules.codeStyle) {
		sections.push(`
## Code Style

- **Indentation**: ${rules.codeStyle.indentation} ${
			rules.codeStyle.rationale?.tabs
				? `(${rules.codeStyle.rationale.tabs})`
				: ""
		}
- **Line limit**: ${rules.codeStyle.lineLimit} characters ${
			rules.codeStyle.rationale?.lineLimit
				? `(${rules.codeStyle.rationale.lineLimit})`
				: ""
		}
- **Semicolons**: ${rules.codeStyle.semicolons ? "Required" : "Forbidden"} ${
			rules.codeStyle.rationale?.semicolons
				? `(${rules.codeStyle.rationale.semicolons})`
				: ""
		}
- **Array type**: ${rules.codeStyle.arrayType} ${
			rules.codeStyle.rationale?.arrayType
				? `(${rules.codeStyle.rationale.arrayType})`
				: ""
		}
- **Variable declarations**: ${
			rules.codeStyle.constOnly ? "const only" : "let/const allowed"
		} ${
			rules.codeStyle.rationale?.constOnly
				? `(${rules.codeStyle.rationale.constOnly})`
				: ""
		}`)
	}

	// Envoy Comments
	if (rules.envoyComments) {
		sections.push(`
## Envoy Comments`)

		if (rules.envoyComments.note) {
			sections.push(`\n${rules.envoyComments.note}`)
		}

		const commentEntries = Object.entries(rules.envoyComments).filter(([key]) =>
			key !== "note"
		)
		if (commentEntries.length > 0) {
			sections.push(`
| Syntax | Purpose |
|--------|---------|
${
				commentEntries.map(([key, value]) => `| \`${key}\` | ${value} |`).join(
					"\n",
				)
			}`)
		}
	}

	// Cognitive Load
	if (rules.cognitiveLoad) {
		sections.push(`
## Cognitive Load

### ${rules.cognitiveLoad.holyGrail}`)

		if (rules.cognitiveLoad.why) {
			sections.push(`
### Why It Matters

${rules.cognitiveLoad.why.map((reason: string) => `- ${reason}`).join("\n")}`)
		}

		if (rules.cognitiveLoad.howRulesServe) {
			sections.push(`
### How Every Rule Serves This Goal

${
				Object.entries(rules.cognitiveLoad.howRulesServe).map(([key, value]) =>
					`- **${key.replace(/([A-Z])/g, " $1").trim()}**: ${value}`
				).join("\n")
			}`)
		}

		if (rules.cognitiveLoad.test) {
			sections.push(`
### The Test

${rules.cognitiveLoad.test}`)
		}

		if (rules.cognitiveLoad.goal) {
			sections.push(`
### The Goal

**${rules.cognitiveLoad.goal}**`)
		}
	}

	// Sacred Oath
	if (rules.sacredOath) {
		sections.push(`
## The Sacred Oath

### ${rules.sacredOath.commitment}

${rules.sacredOath.oaths.map((oath: string) => `- ${oath}`).join("\n")}`)
	}

	// Final Warnings
	if (rules.finalWarnings) {
		sections.push(`
## Final Warnings`)

		if (rules.finalWarnings.performanceConstraints) {
			sections.push(`
### Performance Constraints

${rules.finalWarnings.performanceConstraints}`)
		}

		if (rules.finalWarnings.bottomLine) {
			sections.push(`
### The Bottom Line

**${rules.finalWarnings.bottomLine}**`)
		}

		if (rules.finalWarnings.architectQuote) {
			sections.push(`
---

> _"${rules.finalWarnings.architectQuote}"_
> 
> — ${rules.author}`)
		}
	}

	// Write the file
	writeFileSync(rulesFile.mdPath, sections.join("\n"))

	console.log(`✅ Generated ${relative(projectRoot, rulesFile.mdPath)}`)
	console.log(`   Version: ${rules.version}`)
}

//++ Main function to generate all rules documentation
export default function generateRulesMarkdown(): void {
	console.log("🔍 Finding rules files...")
	const rulesFiles = findRulesFiles()

	if (rulesFiles.length === 0) {
		console.log("❌ No rules files found")
		return
	}

	console.log(
		`📝 Generating markdown for ${rulesFiles.length} rules file(s)...\n`,
	)

	for (const rulesFile of rulesFiles) {
		try {
			generateMarkdownForRules(rulesFile)
		} catch (error) {
			console.error(
				`❌ Failed to generate markdown for ${
					relative(projectRoot, rulesFile.jsonPath)
				}:`,
				error,
			)
		}
	}

	console.log("\n✨ All rules documentation generated successfully!")
}

// Run if called directly
if (import.meta.main) {
	generateRulesMarkdown()
}
