import type {
	BaseComponentProps,
	ExtractLevelProps,
} from "../../../../types/index.ts"
import type IntangibleProps from "../../../../types/Thing/Intangible/index.ts"
import type OfferProps from "../../../../types/Thing/Offer/index.ts"

import Intangible from "./index.tsx"

export type Props = BaseComponentProps<
	OfferProps,
	"Offer",
	ExtractLevelProps<OfferProps, IntangibleProps>
>

export default function Offer(
	{
		acceptedPaymentMethod,
		addOn,
		additionalProperty,
		advanceBookingRequirement,
		aggregateRating,
		areaServed,
		asin,
		availability,
		availabilityEnds,
		availabilityStarts,
		availableAtOrFrom,
		availableDeliveryMethod,
		businessFunction,
		category,
		checkoutPageURLTemplate,
		deliveryLeadTime,
		eligibleCustomerType,
		eligibleDuration,
		eligibleQuantity,
		eligibleRegion,
		eligibleTransactionVolume,
		gtin,
		gtin12,
		gtin13,
		gtin14,
		gtin8,
		hasAdultConsideration,
		hasGS1DigitalLink,
		hasMeasurement,
		hasMerchantReturnPolicy,
		includesObject,
		ineligibleRegion,
		inventoryLevel,
		isFamilyFriendly,
		itemCondition,
		itemOffered,
		leaseLength,
		mobileUrl,
		mpn,
		offeredBy,
		price,
		priceCurrency,
		priceSpecification,
		priceValidUntil,
		review,
		reviews,
		seller,
		serialNumber,
		shippingDetails,
		sku,
		validForMemberTier,
		validFrom,
		validThrough,
		warranty,
		schemaType = "Offer",
		subtypeProperties = {},
		...props
	}: Props,
) {
	return (
		<Intangible
			{...props}
			schemaType={schemaType}
			subtypeProperties={{
				acceptedPaymentMethod,
				addOn,
				additionalProperty,
				advanceBookingRequirement,
				aggregateRating,
				areaServed,
				asin,
				availability,
				availabilityEnds,
				availabilityStarts,
				availableAtOrFrom,
				availableDeliveryMethod,
				businessFunction,
				category,
				checkoutPageURLTemplate,
				deliveryLeadTime,
				eligibleCustomerType,
				eligibleDuration,
				eligibleQuantity,
				eligibleRegion,
				eligibleTransactionVolume,
				gtin,
				gtin12,
				gtin13,
				gtin14,
				gtin8,
				hasAdultConsideration,
				hasGS1DigitalLink,
				hasMeasurement,
				hasMerchantReturnPolicy,
				includesObject,
				ineligibleRegion,
				inventoryLevel,
				isFamilyFriendly,
				itemCondition,
				itemOffered,
				leaseLength,
				mobileUrl,
				mpn,
				offeredBy,
				price,
				priceCurrency,
				priceSpecification,
				priceValidUntil,
				review,
				reviews,
				seller,
				serialNumber,
				shippingDetails,
				sku,
				validForMemberTier,
				validFrom,
				validThrough,
				warranty,
				...subtypeProperties,
			}}
		/>
	)
}
