import {
	composeOperators,
	Constant,
	Divide,
	FromArgument,
	Subtract,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Difference = Subtract("Integer")
const Quotient = Divide("Integer")
const Int = Constant("Integer")
const Arg = FromArgument("Integer")

// Generate an addition with nested division
// from constants and the passed argument
const config = Difference(Quotient(Int(88))(Int(2)))(Arg)

// Run the calculation returning Either<Error, Integer>
const calculate = composeOperators(config)

// Show the config object and the sum
if (code) {
	code.innerHTML = `The configuration generated by Add:

${JSON.stringify(config, null, 2)}

Calculate (88 / 2) - 2:

calculate(2)

The return value: ${JSON.stringify(calculate(2), null, 2)}
`
}
