apiVersion: 1

datasources:
  - name: Thanos
    type: prometheus
    access: proxy
    url: http://thanos-querier:10902
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 2000
    uid: loki-ds
