name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format check
        run: deno task fmt:check

      - name: Lint
        run: deno task lint

      - name: JSX-only guard
        run: deno task lint:no-react-junk

      - name: Type check
        run: deno task type-check

      - name: Components tests (strict)
        run: deno task test:components:strict
