import {
	NaturalLog,
	composeOperators,
	FromArgument,
} from "@sitebender/sitebender"

const code = document.querySelector("#code-output")

const Nat = NaturalLog("Number")
const Arg = FromArgument("Number")

// Generate a natural logarithm operation object
const config = Nat(Arg)

// Generate the composed natural logarithm function
const calculate = composeOperators(config)

// Show the config object and the result
const out =
	"The configuration generated by NaturalLog:\n\n" +
	JSON.stringify(config, null, 2)

if (code) {
	code.innerHTML = out
}

// Check the console below
// e^0 is 1
console.log("calculate(1) ->", calculate(1))
